//! Eager-loaded encoder cache.
//!
//! Spec ref `tokenizer-service-spec-v1alpha1.md` §3.2 (encoder cache):
//!
//! > `Tokenizer::new` 在啟動時 eager-load 所有 dispatch table 中的
//! > encoder assets 到 process memory。Encoder objects 是
//! > immutable + thread-safe (per tiktoken-rs API contract). Hot
//! > path tokenize 無 lock contention。
//!
//! ## Implementation note
//!
//! The vendored encoders for SLICE_03 come from `tiktoken-rs` v0.11
//! which embeds the BPE merges via `include_str!` against its own
//! `assets/*.tiktoken` files. We do TWO things on top:
//!
//!   1. Mirror the same `.tiktoken` files in
//!      `crates/spendguard-tokenizer/data/` and embed them via
//!      `include_bytes!` so we can compute sha256 over the bytes
//!      we control (not the bytes tiktoken-rs controls). This makes
//!      the spec §7.4 integrity check audit-able from this crate's
//!      source tree.
//!   2. Use the tiktoken-rs `*_singleton()` getters at lookup time
//!      so the actual encode path goes through the vetted upstream
//!      implementation — no re-implementation risk.
//!
//! Hot-reload (spec §7.3) is OUT OF SCOPE for SLICE_03 (deferred to
//! SLICE-extra). The cache is built once in [`with_embedded_assets`]
//! and never mutates; concurrent readers see a constant pointer.
//!
//! ## Asset integrity (two layers)
//!
//! Round-2 fix B1 (panel R1+R2 finding): the original SLICE_03 design
//! had a structural soundness gap. We embed our own copies of the
//! `.tiktoken` files under `data/` and sha256 those, but the tokenize
//! hot path goes through `tiktoken_rs::*_singleton()` which uses
//! tiktoken-rs's OWN embedded bytes (different `include_str!`
//! invocation in the upstream crate). The two byte streams may agree
//! today but a tampered tiktoken-rs vendor branch would silently
//! diverge from our verified copy.
//!
//! Layer A — sha256 of our embedded bytes (data/*.tiktoken):
//!   * [`verify_asset_sha256`] is called per encoder at boot.
//!   * Catches an attacker swapping the .tiktoken file in our tree.
//!   * Mismatch → [`TokenizerError::AssetSignatureMismatch`] →
//!     fail-fast per §7.4.
//!
//! Layer B — runtime cross-check assertion against fixture vectors:
//!   * After the tiktoken-rs singletons load (using upstream bytes),
//!     [`cross_check_encoder`] tokenizes the canonical fixture string
//!     `CROSS_CHECK_FIXTURE` with each singleton and asserts the
//!     result equals the hard-coded `EXPECTED_*` token vector.
//!   * Catches divergence between our verified bytes and what the
//!     singletons actually use, so the §7.4 integrity guarantee
//!     extends to the runtime path the hot tokenize call goes through.
//!   * Mismatch → [`TokenizerError::AssetSignatureMismatch`] →
//!     fail-fast per §7.4 (same surface as Layer A so callers see one
//!     code path).
//!
//! Fixture maintenance: when bumping tiktoken-rs, run
//! `cargo run --example discover_fixture_tokens` from the crate root
//! to print the new vectors, then update the EXPECTED_* arrays
//! below. Bumping tiktoken-rs is also the trigger for an
//! asset_sha256 rotation per spec §6.2 — both rotations always
//! happen together.
//!
//! There is NO env-var override for either layer (per §9 review
//! question 3).

use crate::dispatch::{DispatchEntry, TiktokenEncoder};
use crate::error::TokenizerError;
use crate::{Message, TokenizeRequest, TokenizeResponse, ToolCall};
use sha2::{Digest, Sha256};
use tiktoken_rs::CoreBPE;

/// Embedded asset bytes. The bytes here are byte-equal to the
/// tiktoken-rs `assets/*.tiktoken` files of the pinned 0.11.x
/// release; copied into `crates/spendguard-tokenizer/data/` so this
/// crate owns the integrity check.
const ASSET_CL100K_BASE: &[u8] =
    include_bytes!("../data/cl100k_base.tiktoken");
const ASSET_O200K_BASE: &[u8] =
    include_bytes!("../data/o200k_base.tiktoken");
const ASSET_P50K_BASE: &[u8] =
    include_bytes!("../data/p50k_base.tiktoken");

// ============================================================================
// Round-2 fix B1 — cross-check fixture (Layer B integrity guard).
//
// The fixture string is deterministic, unique enough that a generic
// English corpus wouldn't accidentally produce the same vector, and
// short (under 64 chars) so a corrupt encoder fails the check at boot
// without measurable startup latency cost.
//
// The EXPECTED_* arrays were generated by running:
//
//   cargo run --example discover_fixture_tokens
//
// against the currently-pinned tiktoken-rs 0.11.x. When bumping
// tiktoken-rs, re-run the example + update these arrays in lockstep
// with the asset_sha256 rotation (per spec §6.2).
// ============================================================================

/// Cross-check fixture string. Kept short (39 chars) so the fixture
/// vector survives mild encoder version drift without false alarms,
/// yet long enough to span multiple BPE merges and exercise
/// non-trivial dictionary lookups.
const CROSS_CHECK_FIXTURE: &str = "spendguard-cross-check-fixture-v1alpha1";

/// Expected token vector when CROSS_CHECK_FIXTURE is encoded with the
/// cl100k_base singleton from the pinned tiktoken-rs 0.11.x.
const EXPECTED_CL100K_FIXTURE: &[u32] = &[
    2203, 408, 27190, 77529, 16313, 2269, 13025, 8437, 16, 7288, 16,
];

/// Expected token vector when CROSS_CHECK_FIXTURE is encoded with the
/// o200k_base singleton.
const EXPECTED_O200K_FIXTURE: &[u32] = &[
    1148, 419, 29190, 154059, 30411, 52253, 10978, 9827, 16, 15453, 16,
];

/// Expected token vector when CROSS_CHECK_FIXTURE is encoded with the
/// p50k_base singleton.
const EXPECTED_P50K_FIXTURE: &[u32] = &[
    2777, 437, 14864, 12, 19692, 12, 9122, 12, 69, 9602, 12, 85, 16, 26591, 16,
];

/// Per-OpenAI-encoder cache row — a static reference to the
/// pre-built `CoreBPE` plus identity metadata used to populate the
/// `TokenizeResponse` audit fields.
///
/// Round-2 fix m6 (panel finding): previously `encoder: Arc<&'static
/// CoreBPE>`. The Arc was load-bearing in an earlier draft that
/// considered hot-reload, but since SLICE_03 ships with no hot-reload
/// (deferred to SLICE-extra), the `&'static CoreBPE` reference is the
/// natural lifetime — Arc wrapping a static reference is redundant
/// (Arc's reference-counting buys nothing for a 'static borrow).
struct EncoderRow {
    encoder: &'static CoreBPE,
    tiktoken: TiktokenEncoder,
}

/// Eager-loaded encoder bundle.
///
/// Constructed exactly once per [`crate::Tokenizer`] instance via
/// [`with_embedded_assets`]. Holds `&'static CoreBPE` so concurrent
/// worker threads can copy the reference cheaply (Copy trait on
/// references) and call `encoder.encode_with_special_tokens(...)`
/// without locking. When SLICE-extra adds hot-reload, this becomes
/// `Arc<CoreBPE>` (Arc'd value, not Arc'd reference) for atomic swap.
pub struct EncoderCache {
    cl100k: Option<EncoderRow>,
    o200k: Option<EncoderRow>,
    p50k: Option<EncoderRow>,
}

impl EncoderCache {
    /// Verify asset signatures + eager-load all three OpenAI BPE
    /// singletons. Spec §3.2 + §7.4.
    ///
    /// Round-2 fix B1: two-layer integrity check:
    ///   1. Layer A — sha256 of our embedded data/*.tiktoken bytes
    ///      against the asset_sha256 constants.
    ///   2. Layer B — cross-check fixture: tokenize CROSS_CHECK_FIXTURE
    ///      with each singleton and assert the result equals the
    ///      EXPECTED_* hard-coded vectors. Catches divergence between
    ///      our verified bytes and what the singletons actually use.
    pub fn with_embedded_assets() -> Result<Self, TokenizerError> {
        // Layer A — sha256 of the embedded asset bytes.
        verify_asset_sha256("cl100k_base", ASSET_CL100K_BASE, crate::asset_sha256::CL100K_BASE)?;
        verify_asset_sha256("o200k_base", ASSET_O200K_BASE, crate::asset_sha256::O200K_BASE)?;
        verify_asset_sha256("p50k_base", ASSET_P50K_BASE, crate::asset_sha256::P50K_BASE)?;

        // Eager-load via tiktoken-rs singletons. The first call to a
        // singleton triggers `cl100k_base()` / `o200k_base()` etc which
        // parse the embedded base64 → CoreBPE struct. Spec §3.2:
        // encoders are pre-loaded so the hot path has no lazy-init cost.
        let cl100k_ref = tiktoken_rs::cl100k_base_singleton();
        let o200k_ref = tiktoken_rs::o200k_base_singleton();
        let p50k_ref = tiktoken_rs::p50k_base_singleton();

        // Layer B — runtime cross-check against the fixture vector to
        // catch divergence between data/*.tiktoken (we sha256ed) and
        // the bytes the singletons actually use (vendored upstream).
        cross_check_encoder("cl100k_base", cl100k_ref, EXPECTED_CL100K_FIXTURE)?;
        cross_check_encoder("o200k_base", o200k_ref, EXPECTED_O200K_FIXTURE)?;
        cross_check_encoder("p50k_base", p50k_ref, EXPECTED_P50K_FIXTURE)?;

        Ok(Self {
            cl100k: Some(EncoderRow {
                encoder: cl100k_ref,
                tiktoken: TiktokenEncoder::Cl100kBase,
            }),
            o200k: Some(EncoderRow {
                encoder: o200k_ref,
                tiktoken: TiktokenEncoder::O200kBase,
            }),
            p50k: Some(EncoderRow {
                encoder: p50k_ref,
                tiktoken: TiktokenEncoder::P50kBase,
            }),
        })
    }

    /// Test-only constructor: no encoders loaded. Any call into
    /// [`tokenize_with_entry`] returns
    /// [`TokenizerError::AssetLoadFailed`] so the dispatch table
    /// unit tests can verify routing logic without paying the
    /// encoder-load cost on every test process.
    #[doc(hidden)]
    pub fn test_empty() -> Self {
        Self {
            cl100k: None,
            o200k: None,
            p50k: None,
        }
    }

    /// Tokenize using a known dispatch entry.
    ///
    /// Per spec §3.4 the per-chat-message envelope tokens are
    /// added via the upstream `num_tokens_from_messages` helper for
    /// chat models that support it (cl100k_base / o200k_base). For
    /// the p50k_base completion encoders we fall back to raw text
    /// encoding (chat envelope semantics are undefined for
    /// text-completion shape).
    pub fn tokenize_with_entry(
        &self,
        entry: &DispatchEntry,
        req: &TokenizeRequest,
    ) -> Result<TokenizeResponse, TokenizerError> {
        let row = self
            .row_for(entry.tiktoken)
            .ok_or(TokenizerError::AssetLoadFailed {
                encoder: encoder_static_name(entry.tiktoken),
                message: "encoder not loaded (test_empty cache)".to_string(),
            })?;

        let input_tokens = count_tokens(row, req)?;

        Ok(TokenizeResponse {
            input_tokens: input_tokens as i64,
            tier: "T2".to_string(),
            tokenizer_version_id: entry.tiktoken.tokenizer_version_id().to_string(),
            kind: entry.kind.as_str().to_string(),
            fallback_char_count: 0,
            fallback_margin_ratio: 0.0,
            latency_ns: 0,
        })
    }

    fn row_for(&self, enc: TiktokenEncoder) -> Option<&EncoderRow> {
        match enc {
            TiktokenEncoder::Cl100kBase => self.cl100k.as_ref(),
            TiktokenEncoder::O200kBase => self.o200k.as_ref(),
            TiktokenEncoder::P50kBase => self.p50k.as_ref(),
        }
    }
}

/// Compute total token count for a request.
///
/// Per spec §3.4 + §3.5:
///   * Chat shape (messages.len() > 0): per-message envelope
///     (3 tokens / message + per-tool overhead) + 3 reply priming.
///   * Text-completion shape (raw_text.len() > 0): raw encode only.
///   * Both: results from the two branches sum (rare but defensive).
///
/// Round-2 fix m1 (panel finding): per OpenAI cookbook, the legacy
/// gpt-3.5-turbo-0301 snapshot uses tokens_per_message=4 (one extra
/// for an implicit "name" position that newer snapshots dropped).
/// All other cl100k / o200k chat models use 3. We special-case the
/// 0301 snapshot via the request's model string rather than adding
/// a third TiktokenEncoder variant since the BPE encoder itself is
/// still cl100k.
fn count_tokens(row: &EncoderRow, req: &TokenizeRequest) -> Result<usize, TokenizerError> {
    let mut total: usize = 0;

    // ── chat-shape path ───────────────────────────────────────
    if !req.messages.is_empty() {
        let (per_msg_overhead, reply_priming) = match row.tiktoken {
            // Per OpenAI cookbook tokens_per_message=3, plus 3 for
            // reply priming. Holds for cl100k + o200k families
            // shipping in SLICE_03 EXCEPT the legacy 0301 snapshot
            // (R2 m1 fix). p50k models don't use chat shape
            // (text-completion only) — see else branch below.
            TiktokenEncoder::Cl100kBase | TiktokenEncoder::O200kBase => {
                if req.model == "gpt-3.5-turbo-0301" {
                    // Legacy snapshot quirk: tokens_per_message=4.
                    (4usize, 3usize)
                } else {
                    (3usize, 3usize)
                }
            }
            TiktokenEncoder::P50kBase => {
                // Per spec §3.4 — text-completion shape only; if a
                // caller passes messages to p50k, count them as raw
                // (no envelope). This is graceful-degradation rather
                // than rejection.
                (0usize, 0usize)
            }
        };

        for msg in &req.messages {
            total += per_msg_overhead;
            total += encode_count(row, &msg.role)?;
            total += encode_count(row, &msg.content)?;
            for tc in &msg.tool_calls {
                total += tool_call_tokens(row, tc)?;
            }
        }
        total += reply_priming;
    }

    // ── text-completion path ──────────────────────────────────
    if !req.raw_text.is_empty() {
        total += encode_count(row, &req.raw_text)?;
    }

    Ok(total)
}

fn tool_call_tokens(row: &EncoderRow, tc: &ToolCall) -> Result<usize, TokenizerError> {
    // Per tiktoken-rs num_tokens_from_messages: +1 overhead per tool
    // call + tokens(name) + tokens(arguments_json).
    const TOOL_CALL_OVERHEAD: usize = 1;
    Ok(
        TOOL_CALL_OVERHEAD
            + encode_count(row, &tc.name)?
            + encode_count(row, &tc.arguments_json)?,
    )
}

fn encode_count(row: &EncoderRow, text: &str) -> Result<usize, TokenizerError> {
    if text.is_empty() {
        return Ok(0);
    }
    // We capture any panic that might occur inside encode_with_special_tokens
    // and translate to EncoderInternal per spec §8 ("Tier 2 encoder
    // panic during tokenize → hot path raises error → sidecar fail-
    // closed reservation"). The wrapper here is a defense-in-depth
    // (tiktoken-rs's encode_with_special_tokens returns Vec<Rank>
    // and is not expected to panic on well-formed UTF-8).
    //
    // Round-2 fix m6: row.encoder is now `&'static CoreBPE` directly
    // (was `Arc<&'static CoreBPE>`); no Arc deref needed.
    let encoder: &CoreBPE = row.encoder;
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        encoder.encode_with_special_tokens(text).len()
    }));
    result.map_err(|_| TokenizerError::EncoderInternal {
        kind: encoder_static_name(row.tiktoken),
        message: "tiktoken-rs encode panicked on input".to_string(),
    })
}

fn encoder_static_name(enc: TiktokenEncoder) -> &'static str {
    match enc {
        TiktokenEncoder::Cl100kBase => "cl100k_base",
        TiktokenEncoder::O200kBase => "o200k_base",
        TiktokenEncoder::P50kBase => "p50k_base",
    }
}

/// Compute sha256(bytes) and compare against `expected`. Hex
/// comparison is case-insensitive (forced lowercase on the actual
/// side; the `expected` constants live in source as lowercase).
///
/// Round-2 fix m14 (panel finding): use `subtle::ConstantTimeEq` on
/// the decoded `[u8; 32]` bytes instead of `String::eq_ignore_ascii_case`
/// to avoid a (theoretical) timing side-channel on boot. If hex
/// decode of `expected` fails (programmer error — the const is
/// supposed to be a 64-char lowercase hex string), we synthesise an
/// AssetSignatureMismatch with a placeholder so the surface remains
/// "boot fails loudly".
fn verify_asset_sha256(
    encoder: &'static str,
    bytes: &[u8],
    expected: &'static str,
) -> Result<(), TokenizerError> {
    use subtle::ConstantTimeEq;

    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let actual_bytes: [u8; 32] = hasher.finalize().into();
    let actual_hex = hex::encode(actual_bytes);

    // Decode the expected hex. Bad constants are a hard boot failure.
    let expected_vec = match hex::decode(expected) {
        Ok(v) if v.len() == 32 => v,
        _ => {
            return Err(TokenizerError::AssetSignatureMismatch {
                encoder,
                expected,
                actual: format!("expected-const-malformed (got {actual_hex})"),
            });
        }
    };

    // Constant-time compare of the 32-byte sha256 digests.
    if actual_bytes.as_slice().ct_eq(&expected_vec).into() {
        Ok(())
    } else {
        Err(TokenizerError::AssetSignatureMismatch {
            encoder,
            expected,
            actual: actual_hex,
        })
    }
}

/// Round-2 fix B1 (Layer B): cross-check a singleton encoder by
/// tokenizing [`CROSS_CHECK_FIXTURE`] and asserting the result
/// matches the hard-coded fixture vector. Catches the case where
/// tiktoken-rs's vendored bytes diverge from our verified
/// `data/*.tiktoken` copy (Layer A only proves OUR bytes match the
/// sha256; Layer B proves the SINGLETONS are actually using bytes
/// equivalent to ours).
///
/// Re-uses [`TokenizerError::AssetSignatureMismatch`] so the boot-
/// fail surface is one variant for both layers (consumer code only
/// has to map a single error kind).
fn cross_check_encoder(
    encoder: &'static str,
    bpe: &'static CoreBPE,
    expected: &[u32],
) -> Result<(), TokenizerError> {
    let actual = bpe.encode_with_special_tokens(CROSS_CHECK_FIXTURE);
    if actual.as_slice() != expected {
        // Format actual + expected as compact hex-ish for the error
        // log so an operator sees the divergence at a glance. We
        // don't dump them verbatim into the error.expected field
        // (that field is &'static str); we put a stable summary
        // there and the detailed vectors in actual.
        let expected_summary: String = expected
            .iter()
            .take(6)
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(",");
        let actual_summary: String = actual
            .iter()
            .take(6)
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(",");
        return Err(TokenizerError::AssetSignatureMismatch {
            encoder,
            // Static lifetime requirement of the error variant; we
            // store the constant fixture marker so any future code
            // path that inspects `.expected` knows this is a
            // cross-check (Layer B) failure rather than a sha256
            // (Layer A) failure.
            expected: "cross_check_fixture_vector",
            actual: format!(
                "fixture-vector-mismatch: expected first 6 tokens=[{expected_summary}], got=[{actual_summary}]"
            ),
        });
    }
    Ok(())
}

// Suppress unused-import warning when no chat-shape tests run.
#[allow(unused_imports)]
use Message as _Message;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::dispatch::DispatchTable;

    #[test]
    fn asset_signature_check_fails_on_tampered_bytes() {
        // Per §8.1 acceptance — flipping a byte changes the hash,
        // tripping the integrity check.
        let mut tampered = ASSET_CL100K_BASE.to_vec();
        // mutate one byte deep in the file
        if tampered.len() > 1024 {
            tampered[1024] ^= 0x01;
        }
        let err = verify_asset_sha256(
            "cl100k_base",
            &tampered,
            crate::asset_sha256::CL100K_BASE,
        )
        .unwrap_err();
        match err {
            TokenizerError::AssetSignatureMismatch { encoder, .. } => {
                assert_eq!(encoder, "cl100k_base");
            }
            other => panic!("expected AssetSignatureMismatch, got {other:?}"),
        }
    }

    #[test]
    fn cross_check_passes_for_untampered_singletons() {
        // Round-2 fix B1 (Layer B): the cross-check fixture vectors
        // must reproduce exactly against the pinned tiktoken-rs
        // singletons. This pins the boot-fail guard.
        cross_check_encoder(
            "cl100k_base",
            tiktoken_rs::cl100k_base_singleton(),
            EXPECTED_CL100K_FIXTURE,
        )
        .expect("cl100k cross-check passes");
        cross_check_encoder(
            "o200k_base",
            tiktoken_rs::o200k_base_singleton(),
            EXPECTED_O200K_FIXTURE,
        )
        .expect("o200k cross-check passes");
        cross_check_encoder(
            "p50k_base",
            tiktoken_rs::p50k_base_singleton(),
            EXPECTED_P50K_FIXTURE,
        )
        .expect("p50k cross-check passes");
    }

    #[test]
    fn cross_check_fails_on_wrong_expected_vector() {
        // Round-2 fix B1 (Layer B): if EXPECTED_* drifts away from
        // what the singleton produces, boot must fail-fast per §7.4.
        // We simulate by passing a deliberately wrong expected vec.
        let bad_expected: &[u32] = &[1, 2, 3];
        let err = cross_check_encoder(
            "cl100k_base",
            tiktoken_rs::cl100k_base_singleton(),
            bad_expected,
        )
        .expect_err("must fail on wrong expected vector");
        match err {
            TokenizerError::AssetSignatureMismatch {
                encoder,
                expected,
                actual,
            } => {
                assert_eq!(encoder, "cl100k_base");
                assert_eq!(expected, "cross_check_fixture_vector");
                assert!(actual.contains("fixture-vector-mismatch"));
            }
            other => panic!("expected AssetSignatureMismatch (Layer B), got {other:?}"),
        }
    }

    #[test]
    fn asset_signature_check_passes_for_untampered_bytes() {
        verify_asset_sha256(
            "cl100k_base",
            ASSET_CL100K_BASE,
            crate::asset_sha256::CL100K_BASE,
        )
        .expect("untampered bytes pass");
        verify_asset_sha256(
            "o200k_base",
            ASSET_O200K_BASE,
            crate::asset_sha256::O200K_BASE,
        )
        .expect("untampered bytes pass");
        verify_asset_sha256(
            "p50k_base",
            ASSET_P50K_BASE,
            crate::asset_sha256::P50K_BASE,
        )
        .expect("untampered bytes pass");
    }

    #[test]
    fn encoder_cache_loads_with_embedded_assets() {
        // Smoke test — the boot path runs without error.
        let cache = EncoderCache::with_embedded_assets().expect("cache loads");
        assert!(cache.cl100k.is_some());
        assert!(cache.o200k.is_some());
        assert!(cache.p50k.is_some());
    }

    #[test]
    fn tier2_encode_gpt_4o_mini_smoke() {
        let cache = EncoderCache::with_embedded_assets().expect("cache loads");
        let dispatch = DispatchTable::compile().expect("dispatch");
        let entry = dispatch.lookup("gpt-4o-mini").expect("hit");

        let req = TokenizeRequest {
            model: "gpt-4o-mini".to_string(),
            messages: vec![Message {
                role: "user".to_string(),
                content: "hello, world".to_string(),
                tool_calls: vec![],
            }],
            ..Default::default()
        };
        let resp = cache.tokenize_with_entry(entry, &req).expect("encode");
        assert_eq!(resp.tier, "T2");
        assert_eq!(resp.kind, "OPENAI_TIKTOKEN");
        assert!(resp.input_tokens > 0);
        assert_eq!(
            resp.tokenizer_version_id,
            crate::versions::TIKTOKEN_O200K_BASE_VERSION_ID
        );
    }

    #[test]
    fn tier2_encode_gpt_4_smoke() {
        let cache = EncoderCache::with_embedded_assets().expect("cache loads");
        let dispatch = DispatchTable::compile().expect("dispatch");
        let entry = dispatch.lookup("gpt-4").expect("hit");
        let req = TokenizeRequest {
            model: "gpt-4".to_string(),
            messages: vec![Message {
                role: "user".to_string(),
                content: "hello".to_string(),
                tool_calls: vec![],
            }],
            ..Default::default()
        };
        let resp = cache.tokenize_with_entry(entry, &req).expect("encode");
        assert_eq!(
            resp.tokenizer_version_id,
            crate::versions::TIKTOKEN_CL100K_BASE_VERSION_ID
        );
    }

    #[test]
    fn tier2_empty_messages_with_raw_text() {
        let cache = EncoderCache::with_embedded_assets().expect("cache loads");
        let dispatch = DispatchTable::compile().expect("dispatch");
        let entry = dispatch.lookup("text-davinci-003").expect("hit");
        let req = TokenizeRequest {
            model: "text-davinci-003".to_string(),
            raw_text: "hello world".to_string(),
            ..Default::default()
        };
        let resp = cache.tokenize_with_entry(entry, &req).expect("encode");
        assert!(resp.input_tokens > 0);
    }
}
