//! D13 COV_65 — Importer contract + stub.
//!
//! Every live importer (D14 Devin / D15 Manus / D16 Genspark / plus
//! Anthropic Console + OpenAI Admin once those APIs ship) MUST be
//! a function that takes an `ImportRecord` (one row of the vendor's
//! billing report) and returns an `AuditRowDraft` (the SpendGuard
//! audit_outbox row to insert).
//!
//! Spec: docs/specs/coverage/D13_subscription_meter/design.md §5

use chrono::{DateTime, Utc};

/// All vendors a stub importer can target.
///
/// Matches the CHECK constraint on
/// `subscription_import_jobs.importer_kind` (migration 0046).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ImporterKind {
    AnthropicConsoleUsage,
    OpenAiAdminUsage,
    DevinAdminUsage,
    ManusAdminUsage,
    GensparkAdminUsage,
}

impl ImporterKind {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::AnthropicConsoleUsage => "anthropic_console_usage",
            Self::OpenAiAdminUsage => "openai_admin_usage",
            Self::DevinAdminUsage => "devin_admin_usage",
            Self::ManusAdminUsage => "manus_admin_usage",
            Self::GensparkAdminUsage => "genspark_admin_usage",
        }
    }
}

/// One row of a vendor billing report (CSV row or API page item).
///
/// All amounts are in **micro-USD** (atomic) so they survive the
/// import → audit_outbox round trip without floating-point loss.
#[derive(Debug, Clone, PartialEq)]
pub struct ImportRecord {
    pub importer_kind: ImporterKind,
    pub tenant_id: String,
    /// Vendor-supplied workspace / project / org id, opaque.
    pub vendor_subscription_id: String,
    pub model: String,
    pub input_tokens: i64,
    pub output_tokens: i64,
    /// Total amount the vendor billed for this row, micro-USD.
    pub amount_atomic: i64,
    pub window_start: DateTime<Utc>,
    pub window_end: DateTime<Utc>,
}

/// Sentinel string written to audit_outbox.reservation_source for
/// importer-produced rows.  Always `"subscription_meter"` — importer
/// rows are by definition advisory.
pub const MIRROR_AUDIT_COLUMN_RESERVATION_SOURCE: &str = "subscription_meter";

/// Shape of an `audit_outbox` insert produced from an `ImportRecord`.
///
/// This is the contract the live importer must satisfy.  The actual
/// SQL is generated by `services/canonical_ingest` once the live
/// importer lands; this struct is the type-safe handoff.
#[derive(Debug, Clone, PartialEq)]
pub struct AuditRowDraft {
    pub tenant_id: String,
    pub reservation_source: &'static str,
    pub import_source: &'static str,
    pub model: String,
    pub input_tokens: i64,
    pub output_tokens: i64,
    pub amount_atomic: i64,
    pub occurred_at: DateTime<Utc>,
}

/// Convert an `ImportRecord` to the audit_outbox row shape that the
/// importer-job runner will insert.  Stubs in D13; D14/D15/D16 wire
/// the actual SQL emitter.
pub fn import_record_to_audit_row(rec: &ImportRecord) -> AuditRowDraft {
    AuditRowDraft {
        tenant_id: rec.tenant_id.clone(),
        reservation_source: MIRROR_AUDIT_COLUMN_RESERVATION_SOURCE,
        import_source: rec.importer_kind.as_str(),
        model: rec.model.clone(),
        input_tokens: rec.input_tokens.max(0),
        output_tokens: rec.output_tokens.max(0),
        amount_atomic: rec.amount_atomic.max(0),
        // We anchor occurred_at at the window_end so dashboards align
        // with the vendor's billing report cutoff.
        occurred_at: rec.window_end,
    }
}

/// Stub vendor-specific runner.  D14/D15/D16 replace each arm with a
/// real CSV / API client; D13 ships them as no-ops that return an
/// empty vector so callers can wire the job tracker today.
pub fn run_stub_import(_kind: ImporterKind) -> Vec<ImportRecord> {
    // Intentionally empty — D14/D15/D16 land the actual clients.
    Vec::new()
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::TimeZone;

    fn t(y: i32, m: u32, d: u32) -> DateTime<Utc> {
        Utc.with_ymd_and_hms(y, m, d, 0, 0, 0).unwrap()
    }

    #[test]
    fn importer_kind_string_repr_matches_migration_check() {
        // Every variant must produce a string accepted by the
        // CHECK constraint on subscription_import_jobs.importer_kind.
        let kinds = [
            ImporterKind::AnthropicConsoleUsage,
            ImporterKind::OpenAiAdminUsage,
            ImporterKind::DevinAdminUsage,
            ImporterKind::ManusAdminUsage,
            ImporterKind::GensparkAdminUsage,
        ];
        for k in kinds {
            assert!(k.as_str().ends_with("_usage"));
            assert!(!k.as_str().is_empty());
        }
    }

    #[test]
    fn import_record_to_audit_row_carries_subscription_meter() {
        let rec = ImportRecord {
            importer_kind: ImporterKind::AnthropicConsoleUsage,
            tenant_id: "tenant-x".into(),
            vendor_subscription_id: "ws-123".into(),
            model: "claude-3-5-sonnet-20241022".into(),
            input_tokens: 5_000,
            output_tokens: 2_500,
            amount_atomic: 52_500, // $0.0525
            window_start: t(2026, 6, 1),
            window_end: t(2026, 7, 1),
        };
        let row = import_record_to_audit_row(&rec);
        assert_eq!(row.reservation_source, "subscription_meter");
        assert_eq!(row.import_source, "anthropic_console_usage");
        assert_eq!(row.tenant_id, "tenant-x");
        assert_eq!(row.amount_atomic, 52_500);
        assert_eq!(row.occurred_at, t(2026, 7, 1));
    }

    #[test]
    fn import_record_clamps_negative_amounts_to_zero() {
        let rec = ImportRecord {
            importer_kind: ImporterKind::OpenAiAdminUsage,
            tenant_id: "tenant-x".into(),
            vendor_subscription_id: "org-1".into(),
            model: "gpt-4o".into(),
            input_tokens: -5,
            output_tokens: -5,
            amount_atomic: -100,
            window_start: t(2026, 6, 1),
            window_end: t(2026, 7, 1),
        };
        let row = import_record_to_audit_row(&rec);
        assert_eq!(row.input_tokens, 0);
        assert_eq!(row.output_tokens, 0);
        assert_eq!(row.amount_atomic, 0);
    }

    #[test]
    fn stub_runner_returns_empty_vector_for_all_kinds() {
        for k in [
            ImporterKind::AnthropicConsoleUsage,
            ImporterKind::OpenAiAdminUsage,
            ImporterKind::DevinAdminUsage,
            ImporterKind::ManusAdminUsage,
            ImporterKind::GensparkAdminUsage,
        ] {
            let rows = run_stub_import(k);
            assert!(rows.is_empty(), "stub must not produce live data ({:?})", k);
        }
    }
}
