// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_server_none,ts_nocheck,force_optimize_code_size
// @generated from protobuf file "spendguard/tokenizer/v1/tokenizer.proto" (package "spendguard.tokenizer.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// SpendGuard Tokenizer service.
//
// Spec references:
//   - tokenizer-service-spec-v1alpha1.md §2.2 (proto definition)
//   - tokenizer-service-spec-v1alpha1.md §3 (Tier 2 hot path)
//   - tokenizer-service-spec-v1alpha1.md §5 (Tier 3 fallback)
//   - audit-chain-prediction-extension-v1alpha1.md §2.1 (audit columns
//     tokenizer_tier + tokenizer_version_id are populated by Tokenize)
//   - sidecar-architecture-spec-v1alpha1.md §5 (mTLS internal transport)
//
// Transport: gRPC over mTLS (centralized form per §2.1(a)); in-process
// Rust library call (per-pod hot path form per §2.1(b)).
//
// Compatibility: proto3, additive evolution; encoder version surfaced
// via tokenizer_version_id field in TokenizeResponse so audit-chain
// verify-chain can reproduce historical decisions even after an
// encoder refresh (per §7.3).
//
// Protocol-layer cap: max_decoding_message_size = 4 MiB is configured
// server-side in services/tokenizer/src/main.rs. The per-field caps
// below are redundant defense-in-depth and produce field-specific
// InvalidArgument errors after a request has already passed the tonic
// frame cap.
//
// SLICE_03 scope:
//   - Tokenize RPC: Tier 2 OpenAI dispatch + Tier 3 fallback
//   - ShadowVerify RPC: declared but returns UNIMPLEMENTED;
//     SLICE_05 wires the Tier 1 shadow worker
//
// Field-number convention mirrors common.proto:
//   - 1..15  : latency-hot fields (single-byte varint tag)
//   - 16..   : additive / cold fields
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Tokenizer } from "./tokenizer";
import type { ShadowVerifyResponse } from "./tokenizer";
import type { ShadowVerifyRequest } from "./tokenizer";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { TokenizeResponse } from "./tokenizer";
import type { TokenizeRequest } from "./tokenizer";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// Round-2 minor m5 (panel finding): the previous import of
// google/protobuf/timestamp.proto was unused; removed. If a future
// slice adds Timestamp fields (e.g., shadow_verify provider response
// timestamps), re-add the import alongside the field declaration.

/**
 * @generated from protobuf service spendguard.tokenizer.v1.Tokenizer
 */
export interface ITokenizerClient {
    /**
     * Hot-path tokenize. Synchronous; returns Tier 2 result (or Tier 3
     * fallback) under 1ms p99 (library form) / 3ms p99 (gRPC over UDS).
     * Per spec §10.1 latency SLO.
     *
     * @generated from protobuf rpc: Tokenize
     */
    tokenize(input: TokenizeRequest, options?: RpcOptions): UnaryCall<TokenizeRequest, TokenizeResponse>;
    /**
     * Async shadow check via provider count_tokens API. Caller is
     * expected to be the shadow sampling worker, NOT the hot path.
     * Returns Tier 1 (provider-reported) count.
     *
     * SLICE_03: stub — returns gRPC UNIMPLEMENTED. SLICE_05 wires the
     * real shadow worker + Anthropic / Gemini provider clients.
     *
     * @generated from protobuf rpc: ShadowVerify
     */
    shadowVerify(input: ShadowVerifyRequest, options?: RpcOptions): UnaryCall<ShadowVerifyRequest, ShadowVerifyResponse>;
}
// Round-2 minor m5 (panel finding): the previous import of
// google/protobuf/timestamp.proto was unused; removed. If a future
// slice adds Timestamp fields (e.g., shadow_verify provider response
// timestamps), re-add the import alongside the field declaration.

/**
 * @generated from protobuf service spendguard.tokenizer.v1.Tokenizer
 */
export class TokenizerClient implements ITokenizerClient, ServiceInfo {
    typeName = Tokenizer.typeName;
    methods = Tokenizer.methods;
    options = Tokenizer.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Hot-path tokenize. Synchronous; returns Tier 2 result (or Tier 3
     * fallback) under 1ms p99 (library form) / 3ms p99 (gRPC over UDS).
     * Per spec §10.1 latency SLO.
     *
     * @generated from protobuf rpc: Tokenize
     */
    tokenize(input: TokenizeRequest, options?: RpcOptions): UnaryCall<TokenizeRequest, TokenizeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<TokenizeRequest, TokenizeResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Async shadow check via provider count_tokens API. Caller is
     * expected to be the shadow sampling worker, NOT the hot path.
     * Returns Tier 1 (provider-reported) count.
     *
     * SLICE_03: stub — returns gRPC UNIMPLEMENTED. SLICE_05 wires the
     * real shadow worker + Anthropic / Gemini provider clients.
     *
     * @generated from protobuf rpc: ShadowVerify
     */
    shadowVerify(input: ShadowVerifyRequest, options?: RpcOptions): UnaryCall<ShadowVerifyRequest, ShadowVerifyResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ShadowVerifyRequest, ShadowVerifyResponse>("unary", this._transport, method, opt, input);
    }
}
