// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_server_none,ts_nocheck,force_optimize_code_size
// @generated from protobuf file "spendguard/tokenizer/v1/tokenizer.proto" (package "spendguard.tokenizer.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// SpendGuard Tokenizer service.
//
// Spec references:
//   - tokenizer-service-spec-v1alpha1.md §2.2 (proto definition)
//   - tokenizer-service-spec-v1alpha1.md §3 (Tier 2 hot path)
//   - tokenizer-service-spec-v1alpha1.md §5 (Tier 3 fallback)
//   - audit-chain-prediction-extension-v1alpha1.md §2.1 (audit columns
//     tokenizer_tier + tokenizer_version_id are populated by Tokenize)
//   - sidecar-architecture-spec-v1alpha1.md §5 (mTLS internal transport)
//
// Transport: gRPC over mTLS (centralized form per §2.1(a)); in-process
// Rust library call (per-pod hot path form per §2.1(b)).
//
// Compatibility: proto3, additive evolution; encoder version surfaced
// via tokenizer_version_id field in TokenizeResponse so audit-chain
// verify-chain can reproduce historical decisions even after an
// encoder refresh (per §7.3).
//
// Protocol-layer cap: max_decoding_message_size = 4 MiB is configured
// server-side in services/tokenizer/src/main.rs. The per-field caps
// below are redundant defense-in-depth and produce field-specific
// InvalidArgument errors after a request has already passed the tonic
// frame cap.
//
// SLICE_03 scope:
//   - Tokenize RPC: Tier 2 OpenAI dispatch + Tier 3 fallback
//   - ShadowVerify RPC: declared but returns UNIMPLEMENTED;
//     SLICE_05 wires the Tier 1 shadow worker
//
// Field-number convention mirrors common.proto:
//   - 1..15  : latency-hot fields (single-byte varint tag)
//   - 16..   : additive / cold fields
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Round-2 fix M6 + Round-3 fix N3 (DoS protection): the server-side
 * TokenizerSvc rejects requests that exceed the following per-field
 * caps with gRPC InvalidArgument:
 *   model.len()      <= 256 bytes
 *   raw_text.len()   <= 4 MiB
 *   messages.len()   <= 1000 elements
 *   message.content  <= 4 MiB each
 * Plus a protocol-layer cap configured in main.rs:
 *   max_decoding_message_size = 4 MiB     (matches field caps)
 * The protocol cap is the dominant hard cap — anything larger than
 * 4 MiB is rejected by tonic with ResourceExhausted BEFORE proto
 * deserialisation. The field caps are redundant defense-in-depth that
 * also defend the in-process library form (no tonic protocol layer)
 * and provide more specific InvalidArgument errors for callers that
 * want to metric per-field violations. Real workloads sit far below.
 *
 * @generated from protobuf message spendguard.tokenizer.v1.TokenizeRequest
 */
export interface TokenizeRequest {
    /**
     * Required. Model string as appears in the LLM request body
     * (e.g., "gpt-4o-mini", "claude-3-5-sonnet-20240620").
     * Server rejects with InvalidArgument if len > 256 bytes (M6).
     *
     * @generated from protobuf field: string model = 1
     */
    model: string;
    /**
     * Messages array per OpenAI Chat Completions shape; tokenizer
     * applies model-specific message envelope tokens (system + user +
     * assistant role markers + content separators) where applicable.
     * For non-chat models or alternate envelope shapes, use raw_text.
     * Server rejects with InvalidArgument if len > 1000 (M6).
     *
     * @generated from protobuf field: repeated spendguard.tokenizer.v1.TokenizeRequest.Message messages = 2
     */
    messages: TokenizeRequest_Message[];
    /**
     * Mutually exclusive with messages; for text-completion shape.
     * PROTOCOL CAP: 4 MiB.
     * Server rejects with InvalidArgument if len > 4 MiB (M6 / R3 N3 / POST_GA_03 #114).
     *
     * @generated from protobuf field: string raw_text = 3
     */
    rawText: string;
    /**
     * Caller-supplied request_id for tracing/audit; mints UUIDv7 if
     * empty. Non-empty ids must parse as UUIDv7; UUIDv4 remains accepted
     * for backward compatibility and increments a migration metric.
     * Surfaced in tokenize span (per trace-schema-spec §3.1).
     *
     * @generated from protobuf field: string request_id = 4
     */
    requestId: string;
}
/**
 * @generated from protobuf message spendguard.tokenizer.v1.TokenizeRequest.Message
 */
export interface TokenizeRequest_Message {
    /**
     * "system" | "user" | "assistant" | "tool"
     *
     * @generated from protobuf field: string role = 1
     */
    role: string;
    /**
     * Text content; vision/multimodal v2 will add binary
     * content_parts as a separate additive field.
     * PROTOCOL CAP: 4 MiB.
     * Server rejects with InvalidArgument if len > 4 MiB (M6 / R3 N3 / POST_GA_03 #114).
     *
     * @generated from protobuf field: string content = 2
     */
    content: string;
    /**
     * Tool call payload tokens count for tool-using agents.
     * Tokenizer adds function name + arguments JSON encoding to
     * total count using the model's tokenizer.
     *
     * @generated from protobuf field: repeated spendguard.tokenizer.v1.TokenizeRequest.Message.ToolCall tool_calls = 3
     */
    toolCalls: TokenizeRequest_Message_ToolCall[];
}
/**
 * @generated from protobuf message spendguard.tokenizer.v1.TokenizeRequest.Message.ToolCall
 */
export interface TokenizeRequest_Message_ToolCall {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * Canonical JSON encoding of arguments (already serialised).
     *
     * @generated from protobuf field: string arguments_json = 2
     */
    argumentsJson: string;
}
/**
 * @generated from protobuf message spendguard.tokenizer.v1.TokenizeResponse
 */
export interface TokenizeResponse {
    /**
     * Authoritative token count for the input.
     *
     * @generated from protobuf field: int64 input_tokens = 1
     */
    inputTokens: string;
    /**
     * Which tier was used. Always one of T2 | T3 (T1 never on hot
     * path per §1.3 invariant).
     * "T2" | "T3"
     *
     * @generated from protobuf field: string tier = 2
     */
    tier: string;
    /**
     * Encoder version that produced this count. Empty string for
     * Tier 3 (no versioned encoder used). Maps to audit_outbox
     * tokenizer_version_id via the mirror crate
     * (spendguard-prediction-mirror).
     * UUIDv7 of tokenizer_versions row.
     *
     * @generated from protobuf field: string tokenizer_version_id = 3
     */
    tokenizerVersionId: string;
    /**
     * Encoder kind for diagnostics; redundant with version_id but
     * cheap. Mirrors tokenizer_versions.kind CHECK constraint.
     * "OPENAI_TIKTOKEN" | "ANTHROPIC_BPE" | "GEMINI_BPE" |
     * "COHERE_BPE" | "SENTENCEPIECE_LLAMA" | "HEURISTIC"
     *
     * @generated from protobuf field: string kind = 4
     */
    kind: string;
    /**
     * For Tier 3 fallback only: the underlying char count + the
     * conservative margin applied; lets caller log / metric.
     * Both are zero for Tier 2 (proto3 default).
     *
     * @generated from protobuf field: int64 fallback_char_count = 5
     */
    fallbackCharCount: string;
    /**
     * e.g., 1.05 for 5% conservative (per spec §5.1).
     *
     * @generated from protobuf field: float fallback_margin_ratio = 6
     */
    fallbackMarginRatio: number;
    /**
     * Time spent inside Tokenize (excludes RPC overhead). Useful for
     * SLO tracking; not on audit chain.
     *
     * @generated from protobuf field: int64 latency_ns = 7
     */
    latencyNs: string;
}
/**
 * @generated from protobuf message spendguard.tokenizer.v1.ShadowVerifyRequest
 */
export interface ShadowVerifyRequest {
    /**
     * Same shape as TokenizeRequest; shadow worker passes through.
     *
     * @generated from protobuf field: string model = 1
     */
    model: string;
    /**
     * @generated from protobuf field: repeated spendguard.tokenizer.v1.TokenizeRequest.Message messages = 2
     */
    messages: TokenizeRequest_Message[];
    /**
     * @generated from protobuf field: string raw_text = 3
     */
    rawText: string;
    /**
     * Tier 2 result captured at hot-path time, for drift comparison.
     *
     * @generated from protobuf field: int64 t2_input_tokens = 4
     */
    t2InputTokens: string;
    /**
     * @generated from protobuf field: string t2_tokenizer_version_id = 5
     */
    t2TokenizerVersionId: string;
}
/**
 * @generated from protobuf message spendguard.tokenizer.v1.ShadowVerifyResponse
 */
export interface ShadowVerifyResponse {
    /**
     * Provider-reported count.
     *
     * @generated from protobuf field: int64 t1_input_tokens = 1
     */
    t1InputTokens: string;
    /**
     * Absolute drift |T1 - T2| / T1; alert threshold compare against
     * configured per-kind threshold (default 1.0%).
     *
     * @generated from protobuf field: float drift_ratio = 2
     */
    driftRatio: number;
    /**
     * Whether this sample triggered a drift_alert event emission.
     *
     * @generated from protobuf field: bool drift_alert_emitted = 3
     */
    driftAlertEmitted: boolean;
    /**
     * Latency to provider; for circuit-breaker metrics.
     *
     * @generated from protobuf field: int64 provider_latency_ms = 4
     */
    providerLatencyMs: string;
    /**
     * Provider response identifiers for debugging.
     *
     * @generated from protobuf field: string provider_request_id = 5
     */
    providerRequestId: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class TokenizeRequest$Type extends MessageType<TokenizeRequest> {
    constructor() {
        super("spendguard.tokenizer.v1.TokenizeRequest", [
            { no: 1, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "messages", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TokenizeRequest_Message },
            { no: 3, name: "raw_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.tokenizer.v1.TokenizeRequest
 */
export const TokenizeRequest = new TokenizeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TokenizeRequest_Message$Type extends MessageType<TokenizeRequest_Message> {
    constructor() {
        super("spendguard.tokenizer.v1.TokenizeRequest.Message", [
            { no: 1, name: "role", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tool_calls", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TokenizeRequest_Message_ToolCall }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.tokenizer.v1.TokenizeRequest.Message
 */
export const TokenizeRequest_Message = new TokenizeRequest_Message$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TokenizeRequest_Message_ToolCall$Type extends MessageType<TokenizeRequest_Message_ToolCall> {
    constructor() {
        super("spendguard.tokenizer.v1.TokenizeRequest.Message.ToolCall", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "arguments_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.tokenizer.v1.TokenizeRequest.Message.ToolCall
 */
export const TokenizeRequest_Message_ToolCall = new TokenizeRequest_Message_ToolCall$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TokenizeResponse$Type extends MessageType<TokenizeResponse> {
    constructor() {
        super("spendguard.tokenizer.v1.TokenizeResponse", [
            { no: 1, name: "input_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "tier", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "tokenizer_version_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "fallback_char_count", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "fallback_margin_ratio", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 7, name: "latency_ns", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.tokenizer.v1.TokenizeResponse
 */
export const TokenizeResponse = new TokenizeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ShadowVerifyRequest$Type extends MessageType<ShadowVerifyRequest> {
    constructor() {
        super("spendguard.tokenizer.v1.ShadowVerifyRequest", [
            { no: 1, name: "model", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "messages", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TokenizeRequest_Message },
            { no: 3, name: "raw_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "t2_input_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "t2_tokenizer_version_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.tokenizer.v1.ShadowVerifyRequest
 */
export const ShadowVerifyRequest = new ShadowVerifyRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ShadowVerifyResponse$Type extends MessageType<ShadowVerifyResponse> {
    constructor() {
        super("spendguard.tokenizer.v1.ShadowVerifyResponse", [
            { no: 1, name: "t1_input_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "drift_ratio", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 3, name: "drift_alert_emitted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "provider_latency_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "provider_request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.tokenizer.v1.ShadowVerifyResponse
 */
export const ShadowVerifyResponse = new ShadowVerifyResponse$Type();
/**
 * @generated ServiceType for protobuf service spendguard.tokenizer.v1.Tokenizer
 */
export const Tokenizer = new ServiceType("spendguard.tokenizer.v1.Tokenizer", [
    { name: "Tokenize", options: {}, I: TokenizeRequest, O: TokenizeResponse },
    { name: "ShadowVerify", options: {}, I: ShadowVerifyRequest, O: ShadowVerifyResponse }
]);
