// Boundary adapter between the Botpress `llm` interface action shapes and the
// SpendGuard pipeline's simplified internal shapes.
//
// The integration adopts the FORMAL `llm` interface via `.extend(llm, ...)`,
// so the `generateContent` action handler in `src/index.ts` is invoked with
// the interface's rich input (`bp.actions.generateContent.input.Input`) and
// must return the interface's rich output
// (`bp.actions.generateContent.output.Output`). Those shapes carry multipart /
// tool-call content, reasoning controls, tool definitions, and per-token cost
// fields the SpendGuard budget pipeline does not need.
//
// This module narrows the interface input DOWN to `GenerateContentInput` (the
// SpendGuard pipeline only needs the flattened prompt text + the operator
// caps that drive the reserve estimate) and widens the internal
// `GenerateContentOutput` UP to the interface output (filling the interface's
// required `usage.inputCost` / `usage.outputCost`).
//
// The flattening is intentionally lossy: tool-call and image parts are dropped
// to text, since the v1 forward (`src/provider/forward.ts`) emits a single
// text choice and the SpendGuard prompt-hash + token estimate are computed
// over text. This matches the v1 anti-scope (no streaming, no tool calls).
//
// `bp` types are imported as the SINGLE SOURCE OF TRUTH for the interface
// shapes so this adapter stays pinned to the generated `.botpress` contract:
// if `bp build` regenerates a different interface shape, these mappings stop
// type-checking rather than silently drifting.

import type * as bp from "../../.botpress/index.js";
import type { GenerateContentInput, GenerateContentOutput, Message } from "./schemas.js";

/** The interface `generateContent` input, as generated by `bp build`. */
export type InterfaceGenerateContentInput = bp.actions.generateContent.input.Input;
/** The interface `generateContent` output, as generated by `bp build`. */
export type InterfaceGenerateContentOutput = bp.actions.generateContent.output.Output;

type InterfaceMessage = InterfaceGenerateContentInput["messages"][number];
type InterfaceContent = InterfaceMessage["content"];

/**
 * Flatten an interface message `content` (string | multipart array | null) to
 * the plain text the SpendGuard prompt-hash + token estimate operate over.
 * - `null`            -> "" (e.g. an assistant message that is purely tool
 *                        calls carries `content: null`).
 * - `string`          -> as-is.
 * - multipart array   -> the concatenation of the text parts; non-text parts
 *                        (images) contribute nothing to the text estimate.
 */
export function flattenContent(content: InterfaceContent): string {
  if (content === null) {
    return "";
  }
  if (typeof content === "string") {
    return content;
  }
  return content
    .filter((part) => part.type === "text")
    .map((part) => part.text ?? "")
    .join("");
}

/** Map one interface message to the internal `Message` (text-flattened). */
function toInternalMessage(message: InterfaceMessage): Message {
  return { role: message.role, content: flattenContent(message.content) };
}

/**
 * Narrow the interface `generateContent` input to the internal
 * `GenerateContentInput` the SpendGuard pipeline consumes. The interface
 * `modelRef` carries only `{ id }`; the internal model ref mirrors it.
 */
export function toInternalInput(input: InterfaceGenerateContentInput): GenerateContentInput {
  return {
    model: input.model !== undefined ? { id: input.model.id } : undefined,
    messages: input.messages.map(toInternalMessage),
    systemPrompt: input.systemPrompt,
    maxTokens: input.maxTokens,
    temperature: input.temperature,
    topP: input.topP,
    stopSequences: input.stopSequences,
    userId: input.userId,
  };
}

/**
 * Widen the internal `GenerateContentOutput` to the interface output. The
 * interface `usage` requires per-token cost fields the SpendGuard pipeline does
 * not compute (the sidecar ledger is the source of truth for cost); they are
 * reported as 0 and the aggregate advisory `botpress.cost` is preserved.
 */
export function toInterfaceOutput(output: GenerateContentOutput): InterfaceGenerateContentOutput {
  return {
    id: output.id,
    provider: output.provider,
    model: output.model,
    choices: output.choices.map((choice) => ({
      role: choice.role,
      type: choice.type,
      content: choice.content,
      index: choice.index,
      stopReason: choice.stopReason,
    })),
    usage: {
      inputTokens: output.usage.inputTokens,
      inputCost: 0,
      outputTokens: output.usage.outputTokens,
      outputCost: 0,
    },
    botpress: { cost: output.botpress.cost },
  };
}
