#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/release/verify-migration-inventory.sh [--write] [--inventory PATH]

Verify the checked-in SpendGuard migration inventory against direct deploy
migrations in services/*/migrations/*.sql. Nested down/test migrations are
intentionally excluded.
USAGE
}

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

inventory_path="docs/operations/migration-inventory-v1alpha1.txt"
write_inventory=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --write)
      write_inventory=1
      shift
      ;;
    --inventory)
      inventory_path="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ -z "$inventory_path" ]]; then
  echo "--inventory requires a path" >&2
  exit 2
fi

required_services=(
  "services/ledger/migrations"
  "services/canonical_ingest/migrations"
  "services/control_plane/migrations"
)

for service_dir in "${required_services[@]}"; do
  if [[ ! -d "$service_dir" ]]; then
    echo "missing required migration directory: $service_dir" >&2
    exit 1
  fi
  if ! find "$service_dir" -maxdepth 1 -type f -name '*.sql' | grep -q .; then
    echo "missing direct deploy migrations for: $service_dir" >&2
    exit 1
  fi
done

tmp_inventory="$(mktemp)"
tmp_paths="$(mktemp)"
tmp_seen_services="$(mktemp)"
trap 'rm -f "$tmp_inventory" "$tmp_paths" "$tmp_seen_services" /tmp/spendguard-ga04-migration-inventory.diff' EXIT

find services -maxdepth 3 -type f -path 'services/*/migrations/*.sql' | LC_ALL=C sort > "$tmp_paths"

if [[ ! -s "$tmp_paths" ]]; then
  echo "no direct deploy migrations found under services/*/migrations" >&2
  exit 1
fi

sed -E 's#/[^/]+$##' "$tmp_paths" | LC_ALL=C sort -u > "$tmp_seen_services"
for service_dir in "${required_services[@]}"; do
  if ! grep -Fxq "$service_dir" "$tmp_seen_services"; then
    echo "inventory generation missed required service: $service_dir" >&2
    exit 1
  fi
done

{
  printf '# SpendGuard migration inventory v1alpha1\n'
  printf '# Scope: direct deploy migrations only; nested down/test migrations excluded.\n'
  printf '# Generated by scripts/release/verify-migration-inventory.sh --write.\n'
  printf '\n'
  while IFS= read -r migration; do
    checksum="$(shasum -a 256 "$migration" | awk '{print $1}')"
    printf '%s  %s\n' "$checksum" "$migration"
  done < "$tmp_paths"
} > "$tmp_inventory"

if [[ "$write_inventory" -eq 1 ]]; then
  mkdir -p "$(dirname "$inventory_path")"
  cp "$tmp_inventory" "$inventory_path"
  echo "migration inventory written: $inventory_path"
  exit 0
fi

if [[ ! -f "$inventory_path" ]]; then
  echo "missing checked-in migration inventory: $inventory_path" >&2
  echo "run: scripts/release/verify-migration-inventory.sh --write" >&2
  exit 1
fi

if ! diff -u "$inventory_path" "$tmp_inventory" >/tmp/spendguard-ga04-migration-inventory.diff; then
  echo "migration inventory drift detected" >&2
  cat /tmp/spendguard-ga04-migration-inventory.diff >&2
  exit 1
fi

echo "migration inventory verified: $inventory_path"
