// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_server_none,ts_nocheck,force_optimize_code_size
// @generated from protobuf file "spendguard/sidecar_adapter/v1/adapter.proto" (package "spendguard.sidecar_adapter.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// SpendGuard Sidecar ↔ Adapter IPC.
//
// Spec references:
//   - Sidecar Architecture spec v1alpha1 §3 (in_process_adapter +
//     local_sidecar responsibilities), §5 (UDS peer credentials + handshake),
//     §11 (lifecycle drain)
//   - Contract DSL spec v1alpha1 §6 (decision transaction stages),
//     §11 (effect schema + RFC6902 mutation patches), §15 (trigger points),
//     §8 (sub-agent budget grant)
//   - Trace Schema spec v1alpha1 §3.4 (idempotency_key fallback),
//     §7 (span tree + canonical events)
//   - Stage 2 POC Topology spec v1alpha1 §4.6 (adapter publish API
//     idempotency via effect_hash), §11 (adapter UDS gRPC)
//
// Transport: gRPC over Unix Domain Socket (Linux/macOS) or named pipe
// (Windows fallback). Auth: SO_PEERCRED / LOCAL_PEERCRED (per Sidecar §5).
// No mTLS over UDS (peer credentials suffice).
//
// Compatibility: proto3, additive evolution; protocol_handshake negotiates
// version + capability levels.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SidecarAdapter } from "./adapter";
import type { ReleaseReservationResponse } from "./adapter";
import type { ReleaseReservationRequest } from "./adapter";
import type { ResumeAfterApprovalResponse } from "./adapter";
import type { ResumeAfterApprovalRequest } from "./adapter";
import type { DrainSignal } from "./adapter";
import type { DrainSubscribeRequest } from "./adapter";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { ConsumeBudgetGrantResponse } from "./adapter";
import type { ConsumeBudgetGrantRequest } from "./adapter";
import type { RevokeBudgetGrantResponse } from "./adapter";
import type { RevokeBudgetGrantRequest } from "./adapter";
import type { IssueBudgetGrantResponse } from "./adapter";
import type { IssueBudgetGrantRequest } from "./adapter";
import type { TraceEventAck } from "./adapter";
import type { TraceEvent } from "./adapter";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { PublishOutcomeResponse } from "./adapter";
import type { PublishOutcomeRequest } from "./adapter";
import type { DecisionResponse } from "./adapter";
import type { DecisionRequest } from "./adapter";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HandshakeResponse } from "./adapter";
import type { HandshakeRequest } from "./adapter";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
// ============================================================================
// SERVICE
// ============================================================================

/**
 * -- Handshake (per Sidecar §5 protocol_handshake) ------------------------
 *
 * @generated from protobuf service spendguard.sidecar_adapter.v1.SidecarAdapter
 */
export interface ISidecarAdapterClient {
    /**
     * Initial handshake; mandatory before any other RPC. Negotiates SDK version,
     * runtime kind, capability level, tenant_id assertion, key epochs.
     *
     * @generated from protobuf rpc: Handshake
     */
    handshake(input: HandshakeRequest, options?: RpcOptions): UnaryCall<HandshakeRequest, HandshakeResponse>;
    // -- Decision boundary (per Contract §15 trigger points) -----------------

    /**
     * Adapter requests a decision at a *.pre trigger point.
     * Sidecar runs Contract §6 stages 1-5 and returns DecisionResult.
     * Sidecar may take up to Contract §14 latency budget (50ms p99 warm).
     *
     * @generated from protobuf rpc: RequestDecision
     */
    requestDecision(input: DecisionRequest, options?: RpcOptions): UnaryCall<DecisionRequest, DecisionResponse>;
    /**
     * Adapter confirms publish_effect outcome (per Contract §6 stage 7).
     * Idempotent via effect_hash (Stage 2 §4.6).
     *
     * @generated from protobuf rpc: ConfirmPublishOutcome
     */
    confirmPublishOutcome(input: PublishOutcomeRequest, options?: RpcOptions): UnaryCall<PublishOutcomeRequest, PublishOutcomeResponse>;
    // -- Trace events (per Contract §15 *.post triggers; observation only) ---

    /**
     * Adapter emits canonical/lifecycle events (agent.run.start, agent.step.post
     * tool.call.post, llm.call.post for commit, etc.). Server-streamed because
     * sidecar may emit follow-up acks or correction events.
     *
     * @generated from protobuf rpc: EmitTraceEvents
     */
    emitTraceEvents(options?: RpcOptions): DuplexStreamingCall<TraceEvent, TraceEventAck>;
    // -- Sub-agent budget grant (per Contract §8) ----------------------------

    /**
     * Parent agent requests budget_grant JWT to delegate to child agent.
     *
     * @generated from protobuf rpc: IssueBudgetGrant
     */
    issueBudgetGrant(input: IssueBudgetGrantRequest, options?: RpcOptions): UnaryCall<IssueBudgetGrantRequest, IssueBudgetGrantResponse>;
    /**
     * Parent revokes a previously issued grant.
     *
     * @generated from protobuf rpc: RevokeBudgetGrant
     */
    revokeBudgetGrant(input: RevokeBudgetGrantRequest, options?: RpcOptions): UnaryCall<RevokeBudgetGrantRequest, RevokeBudgetGrantResponse>;
    /**
     * Child agent uses grant to bootstrap budget context.
     *
     * @generated from protobuf rpc: ConsumeBudgetGrant
     */
    consumeBudgetGrant(input: ConsumeBudgetGrantRequest, options?: RpcOptions): UnaryCall<ConsumeBudgetGrantRequest, ConsumeBudgetGrantResponse>;
    // -- Lifecycle drain (per Sidecar §11) -----------------------------------

    /**
     * Sidecar signals adapter that drain has begun; adapter should stop
     * initiating new decision boundaries and let in-flight finish.
     *
     * @generated from protobuf rpc: StreamDrainSignal
     */
    streamDrainSignal(input: DrainSubscribeRequest, options?: RpcOptions): ServerStreamingCall<DrainSubscribeRequest, DrainSignal>;
    // -- Approval resume (Phase 5 GA hardening S16) --------------------------

    /**
     * Adapter calls this AFTER the human approver has approved/denied the
     * pending approval (REQUIRE_APPROVAL outcome from RequestDecision).
     * Sidecar:
     *   1. Looks up the approval by (tenant_id, decision_id, approval_id).
     *   2. Reads the current state (must be `approved` or `denied`).
     *   3. For `approved`: re-runs Contract evaluation + Ledger.ReserveSet
     *      with a NEW idempotency key derived from approval_id (so a
     *      replay can never double-publish the effect).
     *   4. For `denied`: emits the deny audit row + returns Decision::STOP.
     *   5. For other states (pending/expired/cancelled): returns the
     *      typed Error code so the adapter raises the right exception.
     *
     * Idempotent: repeated ResumeAfterApproval calls with the same
     * (decision_id, approval_id) produce the same DecisionResponse
     * because the idempotency key includes both.
     *
     * @generated from protobuf rpc: ResumeAfterApproval
     */
    resumeAfterApproval(input: ResumeAfterApprovalRequest, options?: RpcOptions): UnaryCall<ResumeAfterApprovalRequest, ResumeAfterApprovalResponse>;
    // -- Explicit Release (Draft-01 §4 of Agent Spend Protocol) ---------------

    /**
     * Adapter-initiated release of a held reservation before commit.
     * Use when the provider call is aborted, the client times out, or the
     * agent run is cancelled — and the adapter wants to surface that
     * explicitly rather than waiting for an outcome-driven (APPLY_FAILED
     * or trace-event-driven) implicit release.
     *
     * Coexists with the implicit release paths in ConfirmPublishOutcome and
     * EmitTraceEvents; those remain unchanged. Implicit paths are still the
     * default for adapters that report outcomes naturally; the explicit RPC
     * is for adapters that want to match the Agent Spend Protocol Draft-01
     * wire shape (docs/specs/agent-spend-protocol/draft-01.md §4).
     *
     * Idempotent: repeated ReleaseReservation calls with the same
     * (reservation_id, idempotency_key) pair return the original outcome.
     *
     * @generated from protobuf rpc: ReleaseReservation
     */
    releaseReservation(input: ReleaseReservationRequest, options?: RpcOptions): UnaryCall<ReleaseReservationRequest, ReleaseReservationResponse>;
}
// ============================================================================
// SERVICE
// ============================================================================

/**
 * -- Handshake (per Sidecar §5 protocol_handshake) ------------------------
 *
 * @generated from protobuf service spendguard.sidecar_adapter.v1.SidecarAdapter
 */
export class SidecarAdapterClient implements ISidecarAdapterClient, ServiceInfo {
    typeName = SidecarAdapter.typeName;
    methods = SidecarAdapter.methods;
    options = SidecarAdapter.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Initial handshake; mandatory before any other RPC. Negotiates SDK version,
     * runtime kind, capability level, tenant_id assertion, key epochs.
     *
     * @generated from protobuf rpc: Handshake
     */
    handshake(input: HandshakeRequest, options?: RpcOptions): UnaryCall<HandshakeRequest, HandshakeResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HandshakeRequest, HandshakeResponse>("unary", this._transport, method, opt, input);
    }
    // -- Decision boundary (per Contract §15 trigger points) -----------------

    /**
     * Adapter requests a decision at a *.pre trigger point.
     * Sidecar runs Contract §6 stages 1-5 and returns DecisionResult.
     * Sidecar may take up to Contract §14 latency budget (50ms p99 warm).
     *
     * @generated from protobuf rpc: RequestDecision
     */
    requestDecision(input: DecisionRequest, options?: RpcOptions): UnaryCall<DecisionRequest, DecisionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<DecisionRequest, DecisionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Adapter confirms publish_effect outcome (per Contract §6 stage 7).
     * Idempotent via effect_hash (Stage 2 §4.6).
     *
     * @generated from protobuf rpc: ConfirmPublishOutcome
     */
    confirmPublishOutcome(input: PublishOutcomeRequest, options?: RpcOptions): UnaryCall<PublishOutcomeRequest, PublishOutcomeResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<PublishOutcomeRequest, PublishOutcomeResponse>("unary", this._transport, method, opt, input);
    }
    // -- Trace events (per Contract §15 *.post triggers; observation only) ---

    /**
     * Adapter emits canonical/lifecycle events (agent.run.start, agent.step.post
     * tool.call.post, llm.call.post for commit, etc.). Server-streamed because
     * sidecar may emit follow-up acks or correction events.
     *
     * @generated from protobuf rpc: EmitTraceEvents
     */
    emitTraceEvents(options?: RpcOptions): DuplexStreamingCall<TraceEvent, TraceEventAck> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<TraceEvent, TraceEventAck>("duplex", this._transport, method, opt);
    }
    // -- Sub-agent budget grant (per Contract §8) ----------------------------

    /**
     * Parent agent requests budget_grant JWT to delegate to child agent.
     *
     * @generated from protobuf rpc: IssueBudgetGrant
     */
    issueBudgetGrant(input: IssueBudgetGrantRequest, options?: RpcOptions): UnaryCall<IssueBudgetGrantRequest, IssueBudgetGrantResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<IssueBudgetGrantRequest, IssueBudgetGrantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Parent revokes a previously issued grant.
     *
     * @generated from protobuf rpc: RevokeBudgetGrant
     */
    revokeBudgetGrant(input: RevokeBudgetGrantRequest, options?: RpcOptions): UnaryCall<RevokeBudgetGrantRequest, RevokeBudgetGrantResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<RevokeBudgetGrantRequest, RevokeBudgetGrantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Child agent uses grant to bootstrap budget context.
     *
     * @generated from protobuf rpc: ConsumeBudgetGrant
     */
    consumeBudgetGrant(input: ConsumeBudgetGrantRequest, options?: RpcOptions): UnaryCall<ConsumeBudgetGrantRequest, ConsumeBudgetGrantResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConsumeBudgetGrantRequest, ConsumeBudgetGrantResponse>("unary", this._transport, method, opt, input);
    }
    // -- Lifecycle drain (per Sidecar §11) -----------------------------------

    /**
     * Sidecar signals adapter that drain has begun; adapter should stop
     * initiating new decision boundaries and let in-flight finish.
     *
     * @generated from protobuf rpc: StreamDrainSignal
     */
    streamDrainSignal(input: DrainSubscribeRequest, options?: RpcOptions): ServerStreamingCall<DrainSubscribeRequest, DrainSignal> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<DrainSubscribeRequest, DrainSignal>("serverStreaming", this._transport, method, opt, input);
    }
    // -- Approval resume (Phase 5 GA hardening S16) --------------------------

    /**
     * Adapter calls this AFTER the human approver has approved/denied the
     * pending approval (REQUIRE_APPROVAL outcome from RequestDecision).
     * Sidecar:
     *   1. Looks up the approval by (tenant_id, decision_id, approval_id).
     *   2. Reads the current state (must be `approved` or `denied`).
     *   3. For `approved`: re-runs Contract evaluation + Ledger.ReserveSet
     *      with a NEW idempotency key derived from approval_id (so a
     *      replay can never double-publish the effect).
     *   4. For `denied`: emits the deny audit row + returns Decision::STOP.
     *   5. For other states (pending/expired/cancelled): returns the
     *      typed Error code so the adapter raises the right exception.
     *
     * Idempotent: repeated ResumeAfterApproval calls with the same
     * (decision_id, approval_id) produce the same DecisionResponse
     * because the idempotency key includes both.
     *
     * @generated from protobuf rpc: ResumeAfterApproval
     */
    resumeAfterApproval(input: ResumeAfterApprovalRequest, options?: RpcOptions): UnaryCall<ResumeAfterApprovalRequest, ResumeAfterApprovalResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResumeAfterApprovalRequest, ResumeAfterApprovalResponse>("unary", this._transport, method, opt, input);
    }
    // -- Explicit Release (Draft-01 §4 of Agent Spend Protocol) ---------------

    /**
     * Adapter-initiated release of a held reservation before commit.
     * Use when the provider call is aborted, the client times out, or the
     * agent run is cancelled — and the adapter wants to surface that
     * explicitly rather than waiting for an outcome-driven (APPLY_FAILED
     * or trace-event-driven) implicit release.
     *
     * Coexists with the implicit release paths in ConfirmPublishOutcome and
     * EmitTraceEvents; those remain unchanged. Implicit paths are still the
     * default for adapters that report outcomes naturally; the explicit RPC
     * is for adapters that want to match the Agent Spend Protocol Draft-01
     * wire shape (docs/specs/agent-spend-protocol/draft-01.md §4).
     *
     * Idempotent: repeated ReleaseReservation calls with the same
     * (reservation_id, idempotency_key) pair return the original outcome.
     *
     * @generated from protobuf rpc: ReleaseReservation
     */
    releaseReservation(input: ReleaseReservationRequest, options?: RpcOptions): UnaryCall<ReleaseReservationRequest, ReleaseReservationResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReleaseReservationRequest, ReleaseReservationResponse>("unary", this._transport, method, opt, input);
    }
}
