// @generated by protobuf-ts 2.11.1 with parameter long_type_string,force_server_none,ts_nocheck,force_optimize_code_size
// @generated from protobuf file "spendguard/common/v1/common.proto" (package "spendguard.common.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// SpendGuard common types — shared across services.
//
// Spec references:
//   - Contract DSL spec v1alpha1 §12 (Money / Time / Unit schema)
//   - Trace Schema spec v1alpha1 §3 (Identity Split: W3C + UUID v7)
//   - Ledger Storage spec v1alpha1 §3 (Per-Unit Balancing, NUMERIC(38,0))
//   - Stage 2 POC Topology spec v1alpha1 §8 (wire protocol baseline)
//
// Conventions:
//   * UUID v7 IDs:           encoded as RFC 9562 textual string
//   * W3C trace_id/span_id:  encoded as lowercase hex string
//   * NUMERIC(38,0) amounts: encoded as decimal string (no scientific notation)
//   * Timestamps:             RFC 3339 nano via google.protobuf.Timestamp
//   * Signatures:             raw bytes (ed25519 = 64 bytes)
//   * Hashes:                 raw bytes (sha256 = 32 bytes)
//   * Cross-unit comparison:  forbidden in hot path (Contract §12 + Stage 2 §9.4)
//
// Compatibility: proto3, additive evolution; no field removal pre-GA.
//
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../../google/protobuf/timestamp";
// Field-number convention:
//   - 1..15  : latency-hot fields (single-byte varint tag)
//   - 16..   : additive / cold fields
//   - reserved: only declared when a field is removed (not pre-GA;
//               additive evolution per compatibility policy)

// ============================================================================
// IDENTITY (per Trace spec §3)
// ============================================================================

/**
 * W3C trace context (per Trace §3.1).
 *
 * @generated from protobuf message spendguard.common.v1.TraceContext
 */
export interface TraceContext {
    /**
     * 16-byte lowercase hex (e.g., "0af7651916cd43dd8448eb211c80319c").
     *
     * @generated from protobuf field: string trace_id = 1
     */
    traceId: string;
    /**
     * 8-byte lowercase hex (e.g., "00f067aa0ba902b7").
     *
     * @generated from protobuf field: string span_id = 2
     */
    spanId: string;
    /**
     * Optional; required when not_root_span.
     *
     * @generated from protobuf field: string parent_span_id = 3
     */
    parentSpanId: string;
    /**
     * W3C trace state (RFC 9.4); opaque vendor-specific string.
     *
     * @generated from protobuf field: string trace_state = 4
     */
    traceState: string;
}
/**
 * SpendGuard canonical IDs (per Trace §3.2).
 *
 * All IDs are UUID v7 (RFC 9562) for monotonic time-ordering.
 *
 * @generated from protobuf message spendguard.common.v1.SpendGuardIds
 */
export interface SpendGuardIds {
    /**
     * @generated from protobuf field: string run_id = 1
     */
    runId: string; // required at run scope
    /**
     * @generated from protobuf field: string step_id = 2
     */
    stepId: string; // required when span_kind == agent.step
    /**
     * @generated from protobuf field: string llm_call_id = 3
     */
    llmCallId: string; // required when span_kind == llm.call
    /**
     * @generated from protobuf field: string tool_call_id = 4
     */
    toolCallId: string; // required when span_kind == tool.call
    /**
     * @generated from protobuf field: string decision_id = 5
     */
    decisionId: string; // Contract §6 idempotency key
    /**
     * @generated from protobuf field: string snapshot_id = 6
     */
    snapshotId: string;
}
// ============================================================================
// MONEY / UNIT (per Contract §12.1; Ledger §3)
// ============================================================================

/**
 * Unit reference (per Contract §12.1 Money type).
 *
 * Atomic amounts are interpreted relative to a unit's `scale` from Ledger
 * `ledger_units` (e.g., USD scale=6 -> 1 USD = 1_000_000 atomic).
 *
 * Canonical truth is `unit_id` (FK to ledger_units). Convenience fields below
 * are echoed for client-side validation only; ledger derives semantics from
 * unit_id.
 *
 * @generated from protobuf message spendguard.common.v1.UnitRef
 */
export interface UnitRef {
    /**
     * FK to ledger_units.unit_id (UUID v7 string).
     *
     * @generated from protobuf field: string unit_id = 1
     */
    unitId: string;
    /**
     * @generated from protobuf field: spendguard.common.v1.UnitRef.Kind kind = 2
     */
    kind: UnitRef_Kind;
    /**
     * ISO 4217 (when MONETARY); empty otherwise.
     *
     * @generated from protobuf field: string currency = 3
     */
    currency: string;
    /**
     * Token / credit / non_monetary unit_name (when not MONETARY).
     *
     * @generated from protobuf field: string unit_name = 4
     */
    unitName: string;
    /**
     * Token-kind discriminator (per Contract §12.1; required when kind == TOKEN).
     * Examples: "input", "output", "reasoning", "cached_input", "total".
     *
     * @generated from protobuf field: string token_kind = 5
     */
    tokenKind: string;
    /**
     * Model family (per Contract §12.1; required when kind == TOKEN).
     * Tokens of different model families are NOT comparable.
     *
     * @generated from protobuf field: string model_family = 6
     */
    modelFamily: string;
    /**
     * Credit program identifier (per Contract §12.1; required when kind == CREDIT).
     *
     * @generated from protobuf field: string credit_program = 7
     */
    creditProgram: string;
}
/**
 * Convenience kind for client-side validation; canonical truth is unit_id.
 *
 * @generated from protobuf enum spendguard.common.v1.UnitRef.Kind
 */
export enum UnitRef_Kind {
    /**
     * @generated from protobuf enum value: KIND_UNSPECIFIED = 0;
     */
    KIND_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: MONETARY = 1;
     */
    MONETARY = 1,
    /**
     * @generated from protobuf enum value: TOKEN = 2;
     */
    TOKEN = 2,
    /**
     * @generated from protobuf enum value: CREDIT = 3;
     */
    CREDIT = 3,
    /**
     * @generated from protobuf enum value: NON_MONETARY = 4;
     */
    NON_MONETARY = 4
}
/**
 * Atomic amount as decimal string for NUMERIC(38,0) precision.
 *
 * Per Ledger §3: cross-unit comparison forbidden; conversion only at
 * explicit normalization step.
 *
 * @generated from protobuf message spendguard.common.v1.Amount
 */
export interface Amount {
    /**
     * Decimal string, no scientific notation, no thousand separators.
     * Example: "1000000" (= 1.000000 USD when unit.scale=6).
     *
     * @generated from protobuf field: string atomic = 1
     */
    atomic: string;
    /**
     * @generated from protobuf field: spendguard.common.v1.UnitRef unit = 2
     */
    unit?: UnitRef;
}
/**
 * Pricing freeze (per Ledger §13 three-layer freeze).
 *
 * @generated from protobuf message spendguard.common.v1.PricingFreeze
 */
export interface PricingFreeze {
    /**
     * @generated from protobuf field: string pricing_version = 1
     */
    pricingVersion: string; // FOCUS v1.2 + provider snapshot tag
    /**
     * @generated from protobuf field: bytes price_snapshot_hash = 2
     */
    priceSnapshotHash: Uint8Array; // sha256
    /**
     * @generated from protobuf field: string fx_rate_version = 3
     */
    fxRateVersion: string;
    /**
     * @generated from protobuf field: string unit_conversion_version = 4
     */
    unitConversionVersion: string;
}
// ============================================================================
// FENCING (per Sidecar §9; Ledger §9; Stage 2 §4.4)
// ============================================================================

/**
 * @generated from protobuf message spendguard.common.v1.Fencing
 */
export interface Fencing {
    /**
     * @generated from protobuf field: uint64 epoch = 1
     */
    epoch: string;
    /**
     * @generated from protobuf field: string scope_id = 2
     */
    scopeId: string; // FK to fencing_scopes.fencing_scope_id
    /**
     * @generated from protobuf field: string workload_instance_id = 3
     */
    workloadInstanceId: string;
}
// ============================================================================
// REPLAY MINIMAL RESPONSE (per Ledger §7; Stage 2 §8.2.1)
// ============================================================================

/**
 * Minimal replay response — returned after replay window full payload expired.
 *
 * Per Ledger §7: contains no PII / full prompts / encryption keys; only
 * status code, timestamps, and compact resource references.
 *
 * @generated from protobuf message spendguard.common.v1.Replay
 */
export interface Replay {
    /**
     * @generated from protobuf field: string ledger_transaction_id = 1
     */
    ledgerTransactionId: string;
    /**
     * @generated from protobuf field: string operation_kind = 2
     */
    operationKind: string;
    /**
     * @generated from protobuf field: string audit_decision_event_id = 3
     */
    auditDecisionEventId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp recorded_at = 4
     */
    recordedAt?: Timestamp;
    /**
     * Operation-specific compact reference; e.g., reservation_set_id for
     * ReserveSet, refund_credit_event_id for RefundCredit.
     *
     * @generated from protobuf field: string operation_id = 5
     */
    operationId: string;
    /**
     * @generated from protobuf field: spendguard.common.v1.Replay.StatusCode status_code = 6
     */
    statusCode: Replay_StatusCode;
    /**
     * ORIGINAL decision_id from the first call (per Contract §6 / Ledger §7
     * idempotency — same idempotency_key MUST surface the same decision_id
     * across retries). Sidecar uses this on the Replay branch to anchor its
     * response to the original decision, not its locally-minted retry value.
     * Not PII; a server-minted UUID7 identifier.
     *
     * @generated from protobuf field: string decision_id = 7
     */
    decisionId: string;
    /**
     * ORIGINAL projection-side identifiers from the first call, IN CANONICAL
     * ORDER (matching the original Success response order — i.e., claim
     * ordinal). For ReserveSet these are the reservation_ids; for other
     * operations operation-specific (empty for ones that have no per-row
     * projection ids). Required so the adapter sees the same set of resource
     * handles, in the same order, across retries.
     * Not PII; server-minted UUIDs.
     *
     * @generated from protobuf field: repeated string projection_ids = 8
     */
    projectionIds: string[];
    /**
     * ORIGINAL TTL anchor from the first call. For ReserveSet, this is the
     * reservation's ttl_expires_at (the wallclock-derived expiry stored at
     * first-success). The sidecar mirrors this back to the adapter on Replay
     * so that the loser of a concurrent same-key race observes the same TTL
     * as the winner instead of recomputing locally and returning a different
     * wallclock value.
     *
     * @generated from protobuf field: google.protobuf.Timestamp ttl_expires_at = 9
     */
    ttlExpiresAt?: Timestamp;
}
/**
 * Status code retained in minimal replay (per Ledger §7 minimal_replay_response).
 * For terminal states this conveys the final disposition; for in-progress
 * operations this conveys the latest known posting_state code.
 *
 * @generated from protobuf enum spendguard.common.v1.Replay.StatusCode
 */
export enum Replay_StatusCode {
    /**
     * @generated from protobuf enum value: STATUS_CODE_UNSPECIFIED = 0;
     */
    STATUS_CODE_UNSPECIFIED = 0,
    /**
     * ledger_transactions.posting_state = 'posted'
     *
     * @generated from protobuf enum value: POSTED = 1;
     */
    POSTED = 1,
    /**
     * ledger_transactions.posting_state = 'voided'
     *
     * @generated from protobuf enum value: VOIDED = 2;
     */
    VOIDED = 2,
    /**
     * ledger_transactions.posting_state = 'pending'
     *
     * @generated from protobuf enum value: PENDING = 3;
     */
    PENDING = 3
}
/**
 * Full response payload — first-success-only; subject to retention policy.
 *
 * Per Ledger §7: tenant-policy retention (default 24h, max 30d Phase 1).
 *
 * @generated from protobuf message spendguard.common.v1.FullResponsePayload
 */
export interface FullResponsePayload {
    /**
     * Operation-specific full payload; opaque protobuf Any encoded here.
     *
     * @generated from protobuf field: bytes payload = 1
     */
    payload: Uint8Array;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp expires_at = 2
     */
    expiresAt?: Timestamp;
}
// ============================================================================
// ERROR (per Stage 2 §8.2.1)
// ============================================================================

/**
 * @generated from protobuf message spendguard.common.v1.Error
 */
export interface Error {
    /**
     * @generated from protobuf field: spendguard.common.v1.Error.Code code = 1
     */
    code: Error_Code;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
    /**
     * @generated from protobuf field: map<string, string> details = 3
     */
    details: {
        [key: string]: string;
    };
}
/**
 * @generated from protobuf enum spendguard.common.v1.Error.Code
 */
export enum Error_Code {
    /**
     * @generated from protobuf enum value: CODE_UNSPECIFIED = 0;
     */
    CODE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: FENCING_EPOCH_STALE = 1;
     */
    FENCING_EPOCH_STALE = 1,
    /**
     * @generated from protobuf enum value: LOCK_ORDER_TOKEN_MISMATCH = 2;
     */
    LOCK_ORDER_TOKEN_MISMATCH = 2,
    /**
     * @generated from protobuf enum value: PRICING_VERSION_UNKNOWN = 3;
     */
    PRICING_VERSION_UNKNOWN = 3,
    /**
     * @generated from protobuf enum value: UNIT_NORMALIZATION_REQUIRED = 4;
     */
    UNIT_NORMALIZATION_REQUIRED = 4,
    /**
     * @generated from protobuf enum value: BUDGET_EXHAUSTED = 5;
     */
    BUDGET_EXHAUSTED = 5,
    /**
     * @generated from protobuf enum value: DEADLOCK_TIMEOUT = 6;
     */
    DEADLOCK_TIMEOUT = 6,
    /**
     * @generated from protobuf enum value: SYNC_REPLICA_UNAVAILABLE = 7;
     */
    SYNC_REPLICA_UNAVAILABLE = 7,
    /**
     * @generated from protobuf enum value: TENANT_DISABLED = 8;
     */
    TENANT_DISABLED = 8,
    /**
     * @generated from protobuf enum value: SCHEMA_BUNDLE_UNKNOWN = 9;
     */
    SCHEMA_BUNDLE_UNKNOWN = 9,
    /**
     * @generated from protobuf enum value: SIGNATURE_INVALID = 10;
     */
    SIGNATURE_INVALID = 10,
    /**
     * @generated from protobuf enum value: AUDIT_INVARIANT_VIOLATED = 11;
     */
    AUDIT_INVARIANT_VIOLATED = 11,
    /**
     * @generated from protobuf enum value: DUPLICATE_DECISION_EVENT = 12;
     */
    DUPLICATE_DECISION_EVENT = 12,
    /**
     * Phase 2B Step 7: commit lifecycle (Contract §5 / Ledger §10).
     *
     * @generated from protobuf enum value: RESERVATION_STATE_CONFLICT = 13;
     */
    RESERVATION_STATE_CONFLICT = 13,
    /**
     * @generated from protobuf enum value: PRICING_FREEZE_MISMATCH = 14;
     */
    PRICING_FREEZE_MISMATCH = 14,
    /**
     * @generated from protobuf enum value: OVERRUN_RESERVATION = 15;
     */
    OVERRUN_RESERVATION = 15,
    /**
     * @generated from protobuf enum value: RESERVATION_TTL_EXPIRED = 16;
     */
    RESERVATION_TTL_EXPIRED = 16,
    /**
     * @generated from protobuf enum value: MULTI_RESERVATION_COMMIT_DEFERRED = 17;
     */
    MULTI_RESERVATION_COMMIT_DEFERRED = 17,
    /**
     * @generated from protobuf enum value: IDEMPOTENCY_CONFLICT = 18;
     */
    IDEMPOTENCY_CONFLICT = 18
}
// ============================================================================
// BUDGET CLAIM (per Stage 2 §8.2.1)
// ============================================================================

/**
 * @generated from protobuf message spendguard.common.v1.BudgetClaim
 */
export interface BudgetClaim {
    /**
     * @generated from protobuf field: string budget_id = 1
     */
    budgetId: string;
    /**
     * @generated from protobuf field: spendguard.common.v1.UnitRef unit = 2
     */
    unit?: UnitRef;
    /**
     * NUMERIC(38,0) decimal string.
     *
     * @generated from protobuf field: string amount_atomic = 3
     */
    amountAtomic: string;
    /**
     * @generated from protobuf field: spendguard.common.v1.BudgetClaim.Direction direction = 4
     */
    direction: BudgetClaim_Direction;
    /**
     * @generated from protobuf field: string window_instance_id = 5
     */
    windowInstanceId: string;
}
/**
 * @generated from protobuf enum spendguard.common.v1.BudgetClaim.Direction
 */
export enum BudgetClaim_Direction {
    /**
     * @generated from protobuf enum value: DIRECTION_UNSPECIFIED = 0;
     */
    DIRECTION_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: DEBIT = 1;
     */
    DEBIT = 1,
    /**
     * @generated from protobuf enum value: CREDIT = 2;
     */
    CREDIT = 2
}
// ============================================================================
// LOCK ORDER TOKEN (per Stage 2 §8.2.1.1)
// ============================================================================

/**
 * Server derives if omitted; validates if provided.
 *
 * Derivation:
 *   sorted_tuple = sort_lex_by(claims, key=(budget_id, unit.unit_id))
 *   canonical    = ",".join(f"{c.budget_id}:{c.unit.unit_id}" for c in sorted_tuple)
 *   token        = "v1:" + hex(sha256(canonical))
 *
 * @generated from protobuf message spendguard.common.v1.LockOrderToken
 */
export interface LockOrderToken {
    /**
     * @generated from protobuf field: string value = 1
     */
    value: string;
}
// ============================================================================
// CLOUDEVENTS 1.0 ENVELOPE (per Trace §7.5; Stage 2 §8.3)
// ============================================================================

/**
 * CloudEvents 1.0 envelope (structured mode).
 *
 * `data` is opaque payload bytes; type-specific schema lives in canonical
 * schema bundle (Trace §12).
 *
 * @generated from protobuf message spendguard.common.v1.CloudEvent
 */
export interface CloudEvent {
    /**
     * Always "1.0".
     *
     * @generated from protobuf field: string specversion = 1
     */
    specversion: string;
    /**
     * Event type, e.g.:
     *   spendguard.audit.decision
     *   spendguard.audit.outcome
     *   spendguard.ledger.reservation
     *   spendguard.ledger.commit
     *   spendguard.ledger.release
     *   spendguard.approval.requested
     *   spendguard.approval.granted
     *   spendguard.approval.denied
     *   spendguard.approval.expired
     *   spendguard.rollback
     *   spendguard.tombstone
     *   spendguard.refund.credit_received
     *   spendguard.dispute.requested
     *   spendguard.dispute.granted
     *   spendguard.dispute.denied
     *   spendguard.dispute.withdrawn
     *   spendguard.dispute.resolved
     *   spendguard.region_failover_promoted
     *   spendguard.ledger.invoice_reconciled
     *   spendguard.ledger.reconciliation_run
     *
     * @generated from protobuf field: string type = 2
     */
    type: string;
    /**
     * @generated from protobuf field: string source = 3
     */
    source: string; // producer URI
    /**
     * event_id (UUID v7 string); required to be globally unique for dedupe.
     *
     * @generated from protobuf field: string id = 4
     */
    id: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp time = 5
     */
    time?: Timestamp;
    /**
     * Per Trace §7.5 CloudEvents 1.0 envelope: canonical encoding is
     * "application/json" for the `data` field. The `data` field is bytes
     * here (proto3 limitation); content MUST be a JSON document encoded
     * UTF-8 unless `datacontenttype` advertises a different encoding.
     *
     * @generated from protobuf field: string datacontenttype = 6
     */
    datacontenttype: string; // canonical: "application/json"
    /**
     * @generated from protobuf field: bytes data = 7
     */
    data: Uint8Array; // event-specific payload (UTF-8 JSON)
    /**
     * SpendGuard extension attributes (per Trace §7.5 spendguard.* extensions).
     *
     * @generated from protobuf field: string tenant_id = 100
     */
    tenantId: string;
    /**
     * @generated from protobuf field: string run_id = 101
     */
    runId: string;
    /**
     * @generated from protobuf field: string decision_id = 102
     */
    decisionId: string;
    /**
     * @generated from protobuf field: string schema_bundle_id = 103
     */
    schemaBundleId: string; // per Trace §12
    /**
     * Producer signing (per Trace §13).
     *
     * @generated from protobuf field: string producer_id = 200
     */
    producerId: string;
    /**
     * @generated from protobuf field: uint64 producer_sequence = 201
     */
    producerSequence: string;
    /**
     * @generated from protobuf field: bytes producer_signature = 202
     */
    producerSignature: Uint8Array; // ed25519
    /**
     * @generated from protobuf field: string signing_key_id = 203
     */
    signingKeyId: string;
    // ==========================================================================
    // Prediction extension attributes
    // Per docs/audit-chain-prediction-extension-v1alpha1.md §3.2.
    // 
    // Tags 300+. All optional (proto3 default = unset = "field absent on
    // this event"). Wire-level additive evolution: producers populate
    // these on .decision / .outcome events; legacy verifiers ignore them;
    // re-encoded canonical bytes remain byte-identical for rows where
    // these fields are unset (proto3 default-encoding semantics — required
    // by canonical_bytes_proto in services/canonical_ingest/src/verifier.rs).
    // 
    // Decision-side fields populated only on event_type
    //   "spendguard.audit.decision".
    // Outcome-side fields populated only on event_type
    //   "spendguard.audit.outcome".
    // 
    // Sentinel mapping (see §3.3 of the spec):
    //   - run_predicted_remaining_steps = -1  -> "projector unreachable"
    //                                            (distinct from "0 remaining")
    //   - tokenizer_version_id          = ""  -> Tier 3 fallback (no
    //                                            versioned encoder)
    //   - cold_start_layer_used         = ""  -> warm path (no cold start)
    //   - delta_b_ratio                 = 0.0 -> Strategy B was null at
    //                                            decision time
    //   - delta_c_ratio                 = 0.0 -> Strategy C was null at
    //                                            decision time
    // ==========================================================================

    /**
     * Decision-side prediction columns (11 per spec §2.1).
     *
     * @generated from protobuf field: int64 predicted_a_tokens = 300
     */
    predictedATokens: string;
    /**
     * @generated from protobuf field: int64 predicted_b_tokens = 301
     */
    predictedBTokens: string;
    /**
     * @generated from protobuf field: int64 predicted_c_tokens = 302
     */
    predictedCTokens: string;
    /**
     * @generated from protobuf field: string reserved_strategy = 303
     */
    reservedStrategy: string; // "A" | "B" | "C"
    /**
     * @generated from protobuf field: string prediction_strategy_used = 304
     */
    predictionStrategyUsed: string; // "A" | "B" | "C"
    /**
     * @generated from protobuf field: string prediction_policy_used = 305
     */
    predictionPolicyUsed: string; // STRICT_CEILING | EMPIRICAL_RUN_CEILING | ADAPTIVE_CEILING | SHADOW_ONLY
    /**
     * @generated from protobuf field: string tokenizer_tier = 306
     */
    tokenizerTier: string; // "T1" | "T2" | "T3"
    /**
     * @generated from protobuf field: string tokenizer_version_id = 307
     */
    tokenizerVersionId: string; // UUID v7 text; "" on Tier 3
    /**
     * @generated from protobuf field: float prediction_confidence = 308
     */
    predictionConfidence: number; // 0.0-1.0; absent = column-NULL on Strategy A row (see audit-chain-prediction-extension-v1alpha1.md §6.3 + round-2 fix M11). Producers MUST NOT use 0.0 as a sentinel here — calibration-report filters `WHERE prediction_confidence IS NOT NULL`.
    /**
     * Round-3 fix M3: int32 → int64 to match audit_outbox.prediction_sample_size
     * (BIGINT) and audit_outbox.predicted_b_tokens (BIGINT). Eliminates the
     * 2^31 overflow surface on multi-year aggregations without a CHECK
     * constraint workaround. Per round-2 fix M4 the SQL side is already
     * BIGINT — this aligns the wire to match.
     *
     * @generated from protobuf field: int64 prediction_sample_size = 309
     */
    predictionSampleSize: string; // 0 = N/A
    /**
     * @generated from protobuf field: string cold_start_layer_used = 310
     */
    coldStartLayerUsed: string; // "L1" | "L2" | "L3" | "L4"; "" = warm
    /**
     * Run-level projection columns (3 per spec §2.2).
     * NUMERIC(38,0) serialized as int64 here (assumes < 2^63 atomic units;
     * for larger budgets a future v2 may switch to string per Money type).
     *
     * @generated from protobuf field: int64 run_projection_at_decision_atomic = 311
     */
    runProjectionAtDecisionAtomic: string;
    /**
     * @generated from protobuf field: int32 run_predicted_remaining_steps = 312
     */
    runPredictedRemainingSteps: number; // -1 sentinel for unreachable; INT (not BIGINT) on SQL side matches int32 here
    /**
     * Round-4 fix M1: int32 → int64 to match audit_outbox.run_steps_completed_so_far
     * (BIGINT per round-2 fix M4 anticipating multi-year aggregation). Wire-
     * compatible with the round-3 int32 encoding because non-negative
     * values use identical varint wire bytes per proto3 spec; tag 313
     * therefore stays at 313 without a version bump.
     *
     * @generated from protobuf field: int64 run_steps_completed_so_far = 313
     */
    runStepsCompletedSoFar: string;
    /**
     * Commit-side actual columns (4 per spec §2.3). Only on .outcome events.
     *
     * @generated from protobuf field: int64 actual_input_tokens = 314
     */
    actualInputTokens: string;
    /**
     * @generated from protobuf field: int64 actual_output_tokens = 315
     */
    actualOutputTokens: string;
    /**
     * @generated from protobuf field: float delta_b_ratio = 316
     */
    deltaBRatio: number; // 0.0 sentinel = B was null
    /**
     * @generated from protobuf field: float delta_c_ratio = 317
     */
    deltaCRatio: number; // 0.0 sentinel = C was null
}
// ============================================================================
// SCHEMA BUNDLE REFERENCE (per Trace §12)
// ============================================================================

/**
 * @generated from protobuf message spendguard.common.v1.SchemaBundleRef
 */
export interface SchemaBundleRef {
    /**
     * @generated from protobuf field: string schema_bundle_id = 1
     */
    schemaBundleId: string; // UUID v7
    /**
     * @generated from protobuf field: bytes schema_bundle_hash = 2
     */
    schemaBundleHash: Uint8Array; // sha256
    /**
     * @generated from protobuf field: string canonical_schema_version = 3
     */
    canonicalSchemaVersion: string; // e.g., "spendguard.v1alpha1"
}
// ============================================================================
// CONTRACT BUNDLE REFERENCE (per Contract §17)
// ============================================================================

/**
 * @generated from protobuf message spendguard.common.v1.ContractBundleRef
 */
export interface ContractBundleRef {
    /**
     * @generated from protobuf field: string bundle_id = 1
     */
    bundleId: string; // UUID v7
    /**
     * @generated from protobuf field: bytes bundle_hash = 2
     */
    bundleHash: Uint8Array; // sha256
    /**
     * @generated from protobuf field: bytes bundle_signature = 3
     */
    bundleSignature: Uint8Array; // ed25519
    /**
     * @generated from protobuf field: string signing_key_id = 4
     */
    signingKeyId: string;
}
// ============================================================================
// IDEMPOTENCY (per Ledger §7; Stage 2 §8.2.1)
// ============================================================================

/**
 * @generated from protobuf message spendguard.common.v1.Idempotency
 */
export interface Idempotency {
    /**
     * Caller-supplied idempotency key; scoped to (tenant_id, operation_kind).
     *
     * @generated from protobuf field: string key = 1
     */
    key: string;
    /**
     * sha256 of canonical request body for replay-on-retry consistency check.
     *
     * @generated from protobuf field: bytes request_hash = 2
     */
    requestHash: Uint8Array;
}
/**
 * Subscription meter snapshot — returned to the adapter when the
 * classifier routes a request through the subscription meter path.
 * All values are best-effort retail-price estimates in micro-USD.
 *
 * The sidecar does NOT write ledger_entries for these rows; the
 * canonical record lives in `subscription_meters` (migration 0044).
 *
 * @generated from protobuf message spendguard.common.v1.SubscriptionMeter
 */
export interface SubscriptionMeter {
    /**
     * The plan that produced this meter row.
     *
     * @generated from protobuf field: string plan = 1
     */
    plan: string; // "claude_code_pro" | "codex_chatgpt" | "unknown"
    /**
     * Current period (UTC calendar month default).
     *
     * @generated from protobuf field: google.protobuf.Timestamp period_start = 2
     */
    periodStart?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp period_end = 3
     */
    periodEnd?: Timestamp;
    /**
     * Atomic counters (micro-USD).
     *
     * @generated from protobuf field: int64 consumed_atomic = 4
     */
    consumedAtomic: string;
    /**
     * @generated from protobuf field: int64 monthly_cap_atomic = 5
     */
    monthlyCapAtomic: string;
    /**
     * @generated from protobuf field: int64 alert_at_atomic = 6
     */
    alertAtAtomic: string;
    /**
     * 0 means "no hard cap" — kept as int64 (not optional) so legacy
     * decoders read 0 = soft mode.
     *
     * @generated from protobuf field: int64 hard_cap_at_atomic = 7
     */
    hardCapAtAtomic: string;
    /**
     * @generated from protobuf field: spendguard.common.v1.SubscriptionMeter.CapDecision cap_decision = 8
     */
    capDecision: SubscriptionMeter_CapDecision;
    /**
     * For hard-cap blocks only — seconds until window reset, bounded at
     * 86400 (24h) per design §4.5 to prevent CLIs hanging > 24h.
     *
     * @generated from protobuf field: int64 retry_after_seconds = 9
     */
    retryAfterSeconds: string;
}
/**
 * Cap evaluation outcome carried to the adapter.
 *
 * @generated from protobuf enum spendguard.common.v1.SubscriptionMeter.CapDecision
 */
export enum SubscriptionMeter_CapDecision {
    /**
     * @generated from protobuf enum value: CAP_DECISION_UNSPECIFIED = 0;
     */
    CAP_DECISION_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: CAP_PASS = 1;
     */
    CAP_PASS = 1,
    /**
     * @generated from protobuf enum value: CAP_SOFT_ALERT = 2;
     */
    CAP_SOFT_ALERT = 2,
    /**
     * synthetic 429
     *
     * @generated from protobuf enum value: CAP_HARD_BLOCK = 3;
     */
    CAP_HARD_BLOCK = 3
}
// ============================================================================
// SUBSCRIPTION METER (per D13 §4)
// ============================================================================

/**
 * Reservation source: tags an audit_outbox row so dashboards and
 * importers can tell BYOK-charged (real ledger entry) rows apart from
 * subscription-meter (advisory; no ledger entry) rows.
 *
 * Wire-compat: additive enum. RESERVATION_SOURCE_UNSPECIFIED = 0
 * preserves wire-compat for clients emitted before D13.  Legacy rows
 * default to BYOK at the audit_outbox column level (NOT NULL DEFAULT
 * 'byok' per migration 0044).
 *
 * @generated from protobuf enum spendguard.common.v1.ReservationSource
 */
export enum ReservationSource {
    /**
     * @generated from protobuf enum value: RESERVATION_SOURCE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: RESERVATION_SOURCE_BYOK = 1;
     */
    BYOK = 1,
    /**
     * @generated from protobuf enum value: RESERVATION_SOURCE_SUBSCRIPTION_METER = 2;
     */
    SUBSCRIPTION_METER = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class TraceContext$Type extends MessageType<TraceContext> {
    constructor() {
        super("spendguard.common.v1.TraceContext", [
            { no: 1, name: "trace_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "span_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "parent_span_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "trace_state", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.TraceContext
 */
export const TraceContext = new TraceContext$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SpendGuardIds$Type extends MessageType<SpendGuardIds> {
    constructor() {
        super("spendguard.common.v1.SpendGuardIds", [
            { no: 1, name: "run_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "step_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "llm_call_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "tool_call_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "decision_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "snapshot_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.SpendGuardIds
 */
export const SpendGuardIds = new SpendGuardIds$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UnitRef$Type extends MessageType<UnitRef> {
    constructor() {
        super("spendguard.common.v1.UnitRef", [
            { no: 1, name: "unit_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "kind", kind: "enum", T: () => ["spendguard.common.v1.UnitRef.Kind", UnitRef_Kind] },
            { no: 3, name: "currency", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "unit_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "token_kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "model_family", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "credit_program", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.UnitRef
 */
export const UnitRef = new UnitRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Amount$Type extends MessageType<Amount> {
    constructor() {
        super("spendguard.common.v1.Amount", [
            { no: 1, name: "atomic", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "unit", kind: "message", T: () => UnitRef }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.Amount
 */
export const Amount = new Amount$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PricingFreeze$Type extends MessageType<PricingFreeze> {
    constructor() {
        super("spendguard.common.v1.PricingFreeze", [
            { no: 1, name: "pricing_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "price_snapshot_hash", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "fx_rate_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "unit_conversion_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.PricingFreeze
 */
export const PricingFreeze = new PricingFreeze$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Fencing$Type extends MessageType<Fencing> {
    constructor() {
        super("spendguard.common.v1.Fencing", [
            { no: 1, name: "epoch", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "scope_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "workload_instance_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.Fencing
 */
export const Fencing = new Fencing$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Replay$Type extends MessageType<Replay> {
    constructor() {
        super("spendguard.common.v1.Replay", [
            { no: 1, name: "ledger_transaction_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "operation_kind", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "audit_decision_event_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "recorded_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "operation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "status_code", kind: "enum", T: () => ["spendguard.common.v1.Replay.StatusCode", Replay_StatusCode] },
            { no: 7, name: "decision_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "projection_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "ttl_expires_at", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.Replay
 */
export const Replay = new Replay$Type();
// @generated message type with reflection information, may provide speed optimized methods
class FullResponsePayload$Type extends MessageType<FullResponsePayload> {
    constructor() {
        super("spendguard.common.v1.FullResponsePayload", [
            { no: 1, name: "payload", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "expires_at", kind: "message", T: () => Timestamp }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.FullResponsePayload
 */
export const FullResponsePayload = new FullResponsePayload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Error$Type extends MessageType<Error> {
    constructor() {
        super("spendguard.common.v1.Error", [
            { no: 1, name: "code", kind: "enum", T: () => ["spendguard.common.v1.Error.Code", Error_Code] },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "details", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.Error
 */
export const Error = new Error$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BudgetClaim$Type extends MessageType<BudgetClaim> {
    constructor() {
        super("spendguard.common.v1.BudgetClaim", [
            { no: 1, name: "budget_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "unit", kind: "message", T: () => UnitRef },
            { no: 3, name: "amount_atomic", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "direction", kind: "enum", T: () => ["spendguard.common.v1.BudgetClaim.Direction", BudgetClaim_Direction] },
            { no: 5, name: "window_instance_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.BudgetClaim
 */
export const BudgetClaim = new BudgetClaim$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LockOrderToken$Type extends MessageType<LockOrderToken> {
    constructor() {
        super("spendguard.common.v1.LockOrderToken", [
            { no: 1, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.LockOrderToken
 */
export const LockOrderToken = new LockOrderToken$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CloudEvent$Type extends MessageType<CloudEvent> {
    constructor() {
        super("spendguard.common.v1.CloudEvent", [
            { no: 1, name: "specversion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "time", kind: "message", T: () => Timestamp },
            { no: 6, name: "datacontenttype", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 100, name: "tenant_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 101, name: "run_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 102, name: "decision_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 103, name: "schema_bundle_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 200, name: "producer_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 201, name: "producer_sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 202, name: "producer_signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 203, name: "signing_key_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 300, name: "predicted_a_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 301, name: "predicted_b_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 302, name: "predicted_c_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 303, name: "reserved_strategy", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 304, name: "prediction_strategy_used", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 305, name: "prediction_policy_used", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 306, name: "tokenizer_tier", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 307, name: "tokenizer_version_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 308, name: "prediction_confidence", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 309, name: "prediction_sample_size", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 310, name: "cold_start_layer_used", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 311, name: "run_projection_at_decision_atomic", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 312, name: "run_predicted_remaining_steps", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 313, name: "run_steps_completed_so_far", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 314, name: "actual_input_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 315, name: "actual_output_tokens", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 316, name: "delta_b_ratio", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ },
            { no: 317, name: "delta_c_ratio", kind: "scalar", T: 2 /*ScalarType.FLOAT*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.CloudEvent
 */
export const CloudEvent = new CloudEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SchemaBundleRef$Type extends MessageType<SchemaBundleRef> {
    constructor() {
        super("spendguard.common.v1.SchemaBundleRef", [
            { no: 1, name: "schema_bundle_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "schema_bundle_hash", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "canonical_schema_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.SchemaBundleRef
 */
export const SchemaBundleRef = new SchemaBundleRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ContractBundleRef$Type extends MessageType<ContractBundleRef> {
    constructor() {
        super("spendguard.common.v1.ContractBundleRef", [
            { no: 1, name: "bundle_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "bundle_hash", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 3, name: "bundle_signature", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "signing_key_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.ContractBundleRef
 */
export const ContractBundleRef = new ContractBundleRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Idempotency$Type extends MessageType<Idempotency> {
    constructor() {
        super("spendguard.common.v1.Idempotency", [
            { no: 1, name: "key", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request_hash", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.Idempotency
 */
export const Idempotency = new Idempotency$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscriptionMeter$Type extends MessageType<SubscriptionMeter> {
    constructor() {
        super("spendguard.common.v1.SubscriptionMeter", [
            { no: 1, name: "plan", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "period_start", kind: "message", T: () => Timestamp },
            { no: 3, name: "period_end", kind: "message", T: () => Timestamp },
            { no: 4, name: "consumed_atomic", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 5, name: "monthly_cap_atomic", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 6, name: "alert_at_atomic", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 7, name: "hard_cap_at_atomic", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 8, name: "cap_decision", kind: "enum", T: () => ["spendguard.common.v1.SubscriptionMeter.CapDecision", SubscriptionMeter_CapDecision] },
            { no: 9, name: "retry_after_seconds", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spendguard.common.v1.SubscriptionMeter
 */
export const SubscriptionMeter = new SubscriptionMeter$Type();
