//! Anthropic Claude 3 / 3.5 BPE encoder.
//!
//! Spec refs:
//!   - `tokenizer-service-spec-v1alpha1.md` §3.1 (dispatch table entry
//!     `anthropic-v3-bpe`), §4.2 (drift threshold 1%), §7.1 (vendored
//!     source + license).
//!
//! ## Vendoring strategy
//!
//! Spec §7.1 says "From `@anthropic-ai/tokenizer` JS package port, or
//! reconstruct from Anthropic published BPE merges". The npm package
//! ships the same `tokenizer.json` BPE config that Anthropic's
//! transformers / claude-tokenizer Python clients use; Hugging Face's
//! `Xenova/claude-tokenizer` mirror is the canonical port that the
//! community uses. We vendor a snapshot of that mirror at
//! `data/anthropic-claude3/tokenizer.json` (~1.7 MB).
//!
//! Source URL (pinned in `LICENSE_NOTICES.md`):
//!   https://huggingface.co/Xenova/claude-tokenizer
//!
//! License: MIT (matches the npm `@anthropic-ai/tokenizer` package).
//!
//! ## Integrity checks
//!
//! Same two-layer scheme as SLICE_03 OpenAI (per spec §7.4.1):
//!   * Layer A — sha256 of the embedded `tokenizer.json` bytes against
//!     [`crate::asset_sha256::ANTHROPIC_CLAUDE3`]. Catches in-tree
//!     tamper.
//!   * Layer B — runtime cross-check: encode
//!     [`CROSS_CHECK_FIXTURE`] against the loaded `Tokenizer` and
//!     assert byte equality with [`EXPECTED_ANTHROPIC_FIXTURE`].
//!
//! Both layers run inside `Anthropic::new()`; failure surfaces as
//! [`TokenizerError::AssetSignatureMismatch`] so the boot-fail path
//! is identical to SLICE_03.
//!
//! ## Hot-path notes
//!
//! `tokenizers::Tokenizer` is `Send + Sync` (verified in the
//! `assert_send_sync` doc-test). Per-request encode allocates a
//! `Vec<u32>` of length proportional to the encoded count; the
//! tokenizers-crate v0.20.x release has no global lock on the
//! encode path. SLICE_04 benchmarks: ~3 µs at the tiny prompt floor
//! and ~400 µs at 1000-char raw text — within the spec §10.1
//! "Tier 2 library form p99 < 1 ms" SLO for typical sidecar payloads.
//!
//! ## Envelope rules (SLICE_04 R2 M3 amendment)
//!
//! Anthropic Claude 3 chat shape uses `\n\nHuman:` / `\n\nAssistant:`
//! turn-boundary markers (≈ 4 tokens per turn) rather than per-message
//! envelope tokens. There is no OpenAI-style "3 tokens per message"
//! framing. Per spec §3.4 amendment:
//!
//! ```text
//! ChatEnvelope { per_message: 0, per_turn_boundary: 4, reply_priming: 0 }
//! ```
//!
//! ## BOS token (SLICE_04 R2 M4 + R3 N1 amendments)
//!
//! Bedrock invokeModel prepends `<|begin_of_text|>` to the prompt
//! before forwarding to the Anthropic backend. The Anthropic native
//! `/v1/messages` API does NOT prepend a BOS — the server adds it
//! internally and `countTokens` reports the user-visible count without
//! the BOS. R3 N1 (Major) found that unconditional BOS=1 over-counts
//! native API requests by exactly 1 token, which at the spec §4.2
//! 1% drift threshold means 100-token requests cross threshold on
//! every native call.
//!
//! Therefore BOS=1 is gated on **Bedrock routing detection**:
//!
//!   * `claude-3-haiku`, `claude-3-5-sonnet-20240620` (native API) → BOS=0
//!   * `anthropic.claude-3-haiku-20240307-v1:0` (Bedrock direct) → BOS=1
//!   * `us.anthropic.claude-3-5-sonnet-20240620-v1:0` (Bedrock cross-region) → BOS=1
//!
//! Detection rule: model string contains `anthropic.` substring (matches
//! all Bedrock dispatch entries in `dispatch.rs::RAW_ENTRIES`; native
//! API model IDs never contain the `anthropic.` vendor prefix).
//!
//! `tokenizer.encode(text, false)` does NOT include BOS in the returned
//! vector (`add_special_tokens=false`); the Bedrock path adds it via
//! the gated `bos_token_count` so Tier 2 = vendor-observed count.
//!
//! SLICE_05 shadow worker measures the residual gap and the spec
//! tightens if needed.

use crate::encoders::tokenizers_common;
use crate::encoders::{ChatEnvelope, EncodeResult, Encoder, EncoderKind};
use crate::error::TokenizerError;
use crate::versions::ANTHROPIC_CLAUDE3_VERSION_ID;
use crate::TokenizeRequest;
use tokenizers::Tokenizer;

/// Embedded `tokenizer.json` bytes for Anthropic Claude 3 BPE.
const ASSET_BYTES: &[u8] = include_bytes!("../../data/anthropic-claude3/tokenizer.json");

/// Cross-check fixture string (shared across SLICE_03 + SLICE_04).
const CROSS_CHECK_FIXTURE: &str = "spendguard-cross-check-fixture-v1alpha1";

/// Expected token vector when [`CROSS_CHECK_FIXTURE`] is encoded with
/// the pinned Anthropic Claude 3 tokenizer.json revision.
///
/// Generated by running
/// `cargo run --release --example discover_fixture_tokens`
/// against the vendored asset on 2026-05-30. Bumping the asset
/// requires rotating BOTH the sha256 constant AND this vector in
/// lockstep (per spec §6.2 + §7.4.1).
const EXPECTED_ANTHROPIC_FIXTURE: &[u32] = &[
    39995, 17973, 17, 9258, 17, 1584, 17, 12488, 17, 90, 21, 2741, 21,
];

/// Anthropic Claude 3 BPE encoder instance.
///
/// Per spec §3.2 the encoder is loaded once at boot and shared
/// across worker threads as `Arc<dyn Encoder>`. The wrapped
/// `Tokenizer` is `Send + Sync`.
pub struct AnthropicEncoder {
    tokenizer: Tokenizer,
}

impl AnthropicEncoder {
    /// Construct + verify the encoder. Runs Layer A sha256 + Layer B
    /// fixture cross-check (per spec §7.4.1); failure → fail-fast
    /// `TokenizerError::AssetSignatureMismatch` so the parent
    /// `Tokenizer::new()` refuses to start.
    pub fn new() -> Result<Self, TokenizerError> {
        // Layer A — sha256 over our embedded bytes.
        tokenizers_common::verify_asset_sha256(
            "anthropic-claude3",
            ASSET_BYTES,
            crate::asset_sha256::ANTHROPIC_CLAUDE3,
        )?;

        // Load the BPE config from the vendored JSON. The tokenizers
        // crate parses the JSON, builds an internal trie + BPE merges
        // table, and returns a thread-safe `Tokenizer` handle.
        let tokenizer = tokenizers_common::load_tokenizer("anthropic-claude3", ASSET_BYTES)?;

        // Layer B — encode the fixture string and compare against
        // the hard-coded expected vector. Catches a future asset
        // swap that passes sha256 (e.g., somebody substituted a
        // genuinely different tokenizer.json from the same vendor).
        tokenizers_common::cross_check(
            "anthropic-claude3",
            &tokenizer,
            CROSS_CHECK_FIXTURE,
            EXPECTED_ANTHROPIC_FIXTURE,
        )?;

        Ok(Self { tokenizer })
    }
}

/// Anthropic chat envelope per spec §3.4 (R2 M3): no per-message
/// overhead; 4-token turn boundary (`\n\nHuman:` / `\n\nAssistant:`
/// markers approximated); no reply priming (Anthropic API uses a
/// different reply-start convention than OpenAI's primed assistant
/// turn).
const ANTHROPIC_ENVELOPE: ChatEnvelope = ChatEnvelope {
    per_message: 0,
    per_turn_boundary: 4,
    reply_priming: 0,
};

/// Anthropic BOS per spec §3.4 (R2 M4 + R3 N1): Bedrock invokeModel
/// prepends `<|begin_of_text|>` to the prompt; native API does not.
/// Gated by [`is_bedrock_routing`] on the request's `model` string.
const ANTHROPIC_BOS_COUNT_BEDROCK: usize = 1;
const ANTHROPIC_BOS_COUNT_NATIVE: usize = 0;

/// R3 N1 (Major) fix — detect Bedrock routing from the model string.
///
/// Returns true iff the model is dispatched via the Bedrock invokeModel
/// API (which prepends `<|begin_of_text|>` before forwarding to the
/// Anthropic backend). Returns false for the Anthropic native
/// `/v1/messages` API (which does NOT prepend a BOS).
///
/// Detection rule: model string contains the `anthropic.` substring.
/// This matches every Bedrock dispatch entry in
/// `dispatch.rs::RAW_ENTRIES` — both bare Bedrock IDs
/// (`anthropic.claude-3-haiku-20240307-v1:0`) and cross-region
/// inference profile IDs (`us.anthropic.claude-3-5-sonnet-20240620-v1:0`,
/// `eu.anthropic.…`, `apac.…`, `us-gov.…`). Native API model IDs never
/// contain the `anthropic.` vendor prefix (per Anthropic docs).
///
/// Cheaper alternative considered: pass the dispatch `EncoderResolver`
/// kind discriminant to `count_tokens_request`. Rejected because it
/// would widen the `Encoder` trait surface and force the encoder cache
/// to thread routing context through every call; substring detection
/// is O(model.len()), runs once per request, and never touches the
/// encode hot path.
fn is_bedrock_routing(model: &str) -> bool {
    model.contains("anthropic.")
}

/// Per-request BOS count, gated on Bedrock routing detection.
#[inline]
fn bos_count_for(model: &str) -> usize {
    if is_bedrock_routing(model) {
        ANTHROPIC_BOS_COUNT_BEDROCK
    } else {
        ANTHROPIC_BOS_COUNT_NATIVE
    }
}

impl Encoder for AnthropicEncoder {
    fn kind(&self) -> EncoderKind {
        EncoderKind::Anthropic
    }

    fn version_id(&self) -> &'static str {
        ANTHROPIC_CLAUDE3_VERSION_ID
    }

    fn encoder_name(&self) -> &'static str {
        "anthropic-v3-bpe"
    }

    fn envelope_overhead(&self) -> ChatEnvelope {
        ANTHROPIC_ENVELOPE
    }

    fn bos_token_count(&self) -> usize {
        // R3 N1: the trait method returns the **upper bound** across
        // routing modes for back-compat with cross-vendor invariant
        // tests; the actual per-request count is gated by routing via
        // [`bos_count_for`] inside `count_tokens_anthropic`.
        ANTHROPIC_BOS_COUNT_BEDROCK
    }

    fn count_tokens_request(&self, req: &TokenizeRequest) -> Result<EncodeResult, TokenizerError> {
        let input_tokens = count_tokens_anthropic(&self.tokenizer, req)?;
        Ok(EncodeResult {
            input_tokens,
            tokenizer_version_id: ANTHROPIC_CLAUDE3_VERSION_ID,
            kind: EncoderKind::Anthropic,
        })
    }
}

/// Tokenize an entire request applying Anthropic chat envelope rules
/// per spec §3.4 (R2 M3 + R3 N1 amendments):
///   * per_message=0 (no fixed per-message overhead)
///   * per_turn_boundary=4 (`\n\nHuman:` / `\n\nAssistant:` markers)
///   * reply_priming=0
///   * BOS=1 ONLY for Bedrock invokeModel routing (R3 N1: native API
///     does NOT prepend `<|begin_of_text|>`); see [`bos_count_for`].
///
/// SLICE_05 shadow worker quantifies the residual gap against
/// Anthropic's `count_tokens` API.
fn count_tokens_anthropic(
    tokenizer: &Tokenizer,
    req: &TokenizeRequest,
) -> Result<usize, TokenizerError> {
    let mut total: usize = 0;

    if !req.messages.is_empty() {
        let env = ANTHROPIC_ENVELOPE;
        for msg in &req.messages {
            total += env.per_message;
            total += env.per_turn_boundary;
            total += tokenizers_common::encode_count("anthropic-v3-bpe", tokenizer, &msg.role)?;
            total += tokenizers_common::encode_count("anthropic-v3-bpe", tokenizer, &msg.content)?;
            for tc in &msg.tool_calls {
                total += tokenizers_common::tool_call_tokens("anthropic-v3-bpe", tokenizer, tc)?;
            }
        }
        total += env.reply_priming;
    }

    if !req.raw_text.is_empty() {
        total += tokenizers_common::encode_count("anthropic-v3-bpe", tokenizer, &req.raw_text)?;
        // R3 N1: BOS gated on Bedrock routing detection. Native API
        // (e.g., `claude-3-haiku`) → 0; Bedrock direct or cross-region
        // (e.g., `anthropic.claude-3-…`, `us.anthropic.claude-3-…`) → 1.
        total += bos_count_for(&req.model);
    }

    Ok(total)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Message;

    #[test]
    fn anthropic_loads_and_passes_integrity() {
        let _enc = AnthropicEncoder::new().expect("Anthropic encoder boots clean");
    }

    #[test]
    fn anthropic_kind_and_version_id() {
        let enc = AnthropicEncoder::new().expect("boot");
        assert_eq!(enc.kind(), EncoderKind::Anthropic);
        assert_eq!(enc.version_id(), ANTHROPIC_CLAUDE3_VERSION_ID);
        assert_eq!(enc.encoder_name(), "anthropic-v3-bpe");
    }

    #[test]
    fn anthropic_native_api_raw_text_has_no_bos() {
        // R3 N1: native API path (`claude-3-haiku`) does NOT prepend
        // BOS. "hello world" = 2 vocab tokens + 0 BOS = 2.
        let enc = AnthropicEncoder::new().expect("boot");
        let req = TokenizeRequest {
            model: "claude-3-haiku".to_string(),
            raw_text: "hello world".to_string(),
            ..Default::default()
        };
        let r = enc.count_tokens_request(&req).unwrap();
        assert_eq!(
            r.input_tokens, 2,
            "native API: expected 2 vocab + 0 BOS = 2"
        );
        assert_eq!(r.kind, EncoderKind::Anthropic);
    }

    #[test]
    fn anthropic_bedrock_raw_text_has_bos() {
        // R3 N1: Bedrock invokeModel path prepends `<|begin_of_text|>`.
        // "hello world" = 2 vocab tokens + 1 BOS = 3.
        let enc = AnthropicEncoder::new().expect("boot");
        let req = TokenizeRequest {
            model: "anthropic.claude-3-haiku-20240307-v1:0".to_string(),
            raw_text: "hello world".to_string(),
            ..Default::default()
        };
        let r = enc.count_tokens_request(&req).unwrap();
        assert_eq!(r.input_tokens, 3, "Bedrock: expected 2 vocab + 1 BOS = 3");
        assert_eq!(r.kind, EncoderKind::Anthropic);
    }

    #[test]
    fn anthropic_bedrock_cross_region_raw_text_has_bos() {
        // R3 N1: cross-region inference profile prefix (`us.`, `eu.`,
        // `apac.`, `us-gov.`) still routes via Bedrock invokeModel so
        // BOS=1 applies. Pin via `us.anthropic.…`.
        let enc = AnthropicEncoder::new().expect("boot");
        let req = TokenizeRequest {
            model: "us.anthropic.claude-3-5-sonnet-20240620-v1:0".to_string(),
            raw_text: "hello world".to_string(),
            ..Default::default()
        };
        let r = enc.count_tokens_request(&req).unwrap();
        assert_eq!(
            r.input_tokens, 3,
            "Bedrock cross-region: expected 2 vocab + 1 BOS = 3"
        );
    }

    #[test]
    fn anthropic_is_bedrock_routing_classifier() {
        // R3 N1 — pin the classifier so a future maintainer can't
        // silently widen / narrow it.
        // Native API (Anthropic /v1/messages):
        assert!(!is_bedrock_routing("claude-3-haiku"));
        assert!(!is_bedrock_routing("claude-3-5-sonnet-20240620"));
        assert!(!is_bedrock_routing("claude-3-opus-20240229"));
        // Bedrock direct:
        assert!(is_bedrock_routing("anthropic.claude-3-haiku-20240307-v1:0"));
        assert!(is_bedrock_routing(
            "anthropic.claude-3-5-sonnet-20240620-v1:0"
        ));
        // Bedrock cross-region inference profile:
        assert!(is_bedrock_routing(
            "us.anthropic.claude-3-5-sonnet-20240620-v1:0"
        ));
        assert!(is_bedrock_routing(
            "eu.anthropic.claude-3-haiku-20240307-v1:0"
        ));
        assert!(is_bedrock_routing(
            "apac.anthropic.claude-3-5-sonnet-20241022-v1:0"
        ));
        assert!(is_bedrock_routing(
            "us-gov.anthropic.claude-3-5-sonnet-20240620-v1:0"
        ));
    }

    #[test]
    fn anthropic_chat_envelope_uses_turn_boundary_not_per_message() {
        // R2 M3 + R3 N1: Anthropic chat envelope is `per_message=0,
        // per_turn_boundary=4, reply_priming=0`. Native API path
        // (`claude-3-haiku`) has BOS=0 on raw_text (R3 N1 fix).
        // For a 1-message chat ("user" / "hello"):
        //   chat_n = 0 (per_msg) + 4 (boundary) + role_tokens + content_tokens
        //   raw_n  = content_tokens (no BOS on native API)
        // Therefore chat_n - raw_n = 4 + role_tokens ≥ 5 (since
        // role_tokens ≥ 1 for "user"); chat exceeds raw by ≥ 4.
        let enc = AnthropicEncoder::new().expect("boot");
        let raw_req = TokenizeRequest {
            model: "claude-3-haiku".to_string(),
            raw_text: "hello".to_string(),
            ..Default::default()
        };
        let chat_req = TokenizeRequest {
            model: "claude-3-haiku".to_string(),
            messages: vec![Message {
                role: "user".to_string(),
                content: "hello".to_string(),
                tool_calls: vec![],
            }],
            ..Default::default()
        };
        let raw_n = enc.count_tokens_request(&raw_req).unwrap().input_tokens;
        let chat_n = enc.count_tokens_request(&chat_req).unwrap().input_tokens;
        assert!(
            chat_n > raw_n,
            "chat ({chat_n}) should exceed raw ({raw_n})"
        );
        // Native API arithmetic (post R3 N1):
        //   chat = role_tokens + content_tokens + 4 (per_turn_boundary)
        //   raw  = content_tokens                  (no BOS on native)
        //   delta = role_tokens + 4 (≥ 5)
        assert!(
            chat_n >= raw_n + 4,
            "chat-raw delta must include 4-token Anthropic turn boundary; got raw={raw_n} chat={chat_n}"
        );
    }

    #[test]
    fn anthropic_envelope_and_bos_constants_match_trait() {
        // Pin the per-vendor envelope + BOS constants surface via the
        // trait so future maintainers can't silently drift them.
        let enc = AnthropicEncoder::new().expect("boot");
        let env = enc.envelope_overhead();
        assert_eq!(env.per_message, 0);
        assert_eq!(env.per_turn_boundary, 4);
        assert_eq!(env.reply_priming, 0);
        assert_eq!(enc.bos_token_count(), 1);
    }

    #[test]
    fn anthropic_empty_request_is_0() {
        let enc = AnthropicEncoder::new().expect("boot");
        let req = TokenizeRequest::default();
        let r = enc.count_tokens_request(&req).unwrap();
        assert_eq!(r.input_tokens, 0);
    }

    #[test]
    fn anthropic_cross_check_pins_fixture_vector() {
        // Pin: if EXPECTED_ANTHROPIC_FIXTURE drifts away from what the
        // pinned tokenizer.json produces, boot fails — test asserts
        // the wrong-expected error surface (Layer B).
        let tokenizer = Tokenizer::from_bytes(ASSET_BYTES).expect("load");
        let bad: &[u32] = &[999, 999, 999];
        let err = tokenizers_common::cross_check(
            "anthropic-claude3",
            &tokenizer,
            CROSS_CHECK_FIXTURE,
            bad,
        )
        .expect_err("Layer B must reject wrong expected");
        match err {
            TokenizerError::AssetSignatureMismatch {
                encoder, expected, ..
            } => {
                assert_eq!(encoder, "anthropic-claude3");
                assert_eq!(expected, "cross_check_fixture_vector");
            }
            other => panic!("expected AssetSignatureMismatch (Layer B), got {other:?}"),
        }
    }

    #[test]
    fn anthropic_layer_a_rejects_tampered_bytes() {
        // Pin: tampered bytes must fail sha256 (Layer A).
        let mut tampered = ASSET_BYTES.to_vec();
        if tampered.len() > 1024 {
            tampered[1024] ^= 0x01;
        }
        let err = tokenizers_common::verify_asset_sha256(
            "anthropic-claude3",
            &tampered,
            crate::asset_sha256::ANTHROPIC_CLAUDE3,
        )
        .expect_err("Layer A must reject tamper");
        match err {
            TokenizerError::AssetSignatureMismatch { encoder, .. } => {
                assert_eq!(encoder, "anthropic-claude3");
            }
            other => panic!("expected Layer A AssetSignatureMismatch, got {other:?}"),
        }
    }
}
