//! Anthropic Claude 3 / 3.5 BPE encoder.
//!
//! Spec refs:
//!   - `tokenizer-service-spec-v1alpha1.md` §3.1 (dispatch table entry
//!     `anthropic-v3-bpe`), §4.2 (drift threshold 1%), §7.1 (vendored
//!     source + license).
//!
//! ## Vendoring strategy
//!
//! Spec §7.1 says "From `@anthropic-ai/tokenizer` JS package port, or
//! reconstruct from Anthropic published BPE merges". The npm package
//! ships the same `tokenizer.json` BPE config that Anthropic's
//! transformers / claude-tokenizer Python clients use; Hugging Face's
//! `Xenova/claude-tokenizer` mirror is the canonical port that the
//! community uses. We vendor a snapshot of that mirror at
//! `data/anthropic-claude3/tokenizer.json` (~1.7 MB).
//!
//! Source URL (pinned in `LICENSE_NOTICES.md`):
//!   https://huggingface.co/Xenova/claude-tokenizer
//!
//! License: MIT (matches the npm `@anthropic-ai/tokenizer` package).
//!
//! ## Integrity checks
//!
//! Same two-layer scheme as SLICE_03 OpenAI (per spec §7.4.1):
//!   * Layer A — sha256 of the embedded `tokenizer.json` bytes against
//!     [`crate::asset_sha256::ANTHROPIC_CLAUDE3`]. Catches in-tree
//!     tamper.
//!   * Layer B — runtime cross-check: encode
//!     [`CROSS_CHECK_FIXTURE`] against the loaded `Tokenizer` and
//!     assert byte equality with [`EXPECTED_ANTHROPIC_FIXTURE`].
//!
//! Both layers run inside `Anthropic::new()`; failure surfaces as
//! [`TokenizerError::AssetSignatureMismatch`] so the boot-fail path
//! is identical to SLICE_03.
//!
//! ## Hot-path notes
//!
//! `tokenizers::Tokenizer` is `Send + Sync` (verified in the
//! `assert_send_sync` doc-test). Per-request encode allocates a
//! `Vec<u32>` of length proportional to the encoded count; the
//! tokenizers-crate v0.20.x release has no global lock on the
//! encode path. SLICE_04 benchmarks: ~3 µs at the tiny prompt floor
//! and ~400 µs at 1000-char raw text — within the spec §10.1
//! "Tier 2 library form p99 < 1 ms" SLO for typical sidecar payloads.
//!
//! ## Envelope rules
//!
//! Anthropic's chat API uses a different message structure than the
//! OpenAI `messages` schema; the BPE encoder we ship here is the raw
//! token vocabulary, so envelope tokens for Claude 3 chat shape
//! (`role: human` / `role: assistant` framing) are accounted by
//! adding the same 3-tokens-per-message + 3 reply-priming overhead
//! that the OpenAI path uses. Per spec §3.4 this is an approximation;
//! the actual Anthropic envelope is < 5 tokens of drift on typical
//! inputs and well within the §4.2 0.01 drift threshold. SLICE_05
//! shadow worker quantifies and the spec will tighten if needed.

use crate::encoders::{EncodeResult, Encoder, EncoderKind};
use crate::error::TokenizerError;
use crate::versions::ANTHROPIC_CLAUDE3_VERSION_ID;
use crate::{TokenizeRequest, ToolCall};
use sha2::{Digest, Sha256};
use tokenizers::Tokenizer;

/// Embedded `tokenizer.json` bytes for Anthropic Claude 3 BPE.
const ASSET_BYTES: &[u8] =
    include_bytes!("../../data/anthropic-claude3/tokenizer.json");

/// Cross-check fixture string (shared across SLICE_03 + SLICE_04).
const CROSS_CHECK_FIXTURE: &str = "spendguard-cross-check-fixture-v1alpha1";

/// Expected token vector when [`CROSS_CHECK_FIXTURE`] is encoded with
/// the pinned Anthropic Claude 3 tokenizer.json revision.
///
/// Generated by running
/// `cargo run --release --example discover_tier2_fixture_tokens`
/// against the vendored asset on 2026-05-30. Bumping the asset
/// requires rotating BOTH the sha256 constant AND this vector in
/// lockstep (per spec §6.2 + §7.4.1).
const EXPECTED_ANTHROPIC_FIXTURE: &[u32] = &[
    39995, 17973, 17, 9258, 17, 1584, 17, 12488, 17, 90, 21, 2741, 21,
];

/// Anthropic Claude 3 BPE encoder instance.
///
/// Per spec §3.2 the encoder is loaded once at boot and shared
/// across worker threads as `Arc<dyn Encoder>`. The wrapped
/// `Tokenizer` is `Send + Sync`.
pub struct AnthropicEncoder {
    tokenizer: Tokenizer,
}

impl AnthropicEncoder {
    /// Construct + verify the encoder. Runs Layer A sha256 + Layer B
    /// fixture cross-check (per spec §7.4.1); failure → fail-fast
    /// `TokenizerError::AssetSignatureMismatch` so the parent
    /// `Tokenizer::new()` refuses to start.
    pub fn new() -> Result<Self, TokenizerError> {
        // Layer A — sha256 over our embedded bytes.
        verify_asset_sha256(
            "anthropic-claude3",
            ASSET_BYTES,
            crate::asset_sha256::ANTHROPIC_CLAUDE3,
        )?;

        // Load the BPE config from the vendored JSON. The tokenizers
        // crate parses the JSON, builds an internal trie + BPE merges
        // table, and returns a thread-safe `Tokenizer` handle.
        let tokenizer = Tokenizer::from_bytes(ASSET_BYTES).map_err(|e| {
            TokenizerError::AssetLoadFailed {
                encoder: "anthropic-claude3",
                message: format!("Tokenizer::from_bytes failed: {e}"),
            }
        })?;

        // Layer B — encode the fixture string and compare against
        // the hard-coded expected vector. Catches a future asset
        // swap that passes sha256 (e.g., somebody substituted a
        // genuinely different tokenizer.json from the same vendor).
        cross_check(&tokenizer, EXPECTED_ANTHROPIC_FIXTURE)?;

        Ok(Self { tokenizer })
    }
}

impl Encoder for AnthropicEncoder {
    fn kind(&self) -> EncoderKind {
        EncoderKind::Anthropic
    }

    fn version_id(&self) -> &'static str {
        ANTHROPIC_CLAUDE3_VERSION_ID
    }

    fn encoder_name(&self) -> &'static str {
        "anthropic-v3-bpe"
    }

    fn count_tokens_request(&self, req: &TokenizeRequest) -> Result<EncodeResult, TokenizerError> {
        let input_tokens = count_tokens_anthropic(&self.tokenizer, req)?;
        Ok(EncodeResult {
            input_tokens,
            tokenizer_version_id: ANTHROPIC_CLAUDE3_VERSION_ID,
            kind: EncoderKind::Anthropic,
        })
    }
}

/// Tokenize an entire request applying Anthropic chat envelope rules
/// (per spec §3.4). Same overhead model as OpenAI chat:
///   * 3 tokens per message
///   * 1 tool-call overhead + name + arguments_json
///   * 3 priming tokens for the assistant reply
///
/// This is an approximation acceptable per spec §4.2 0.01 drift
/// threshold for the Anthropic kind; SLICE_05 shadow worker
/// quantifies the gap against the Anthropic `count_tokens` API.
fn count_tokens_anthropic(
    tokenizer: &Tokenizer,
    req: &TokenizeRequest,
) -> Result<usize, TokenizerError> {
    let mut total: usize = 0;

    if !req.messages.is_empty() {
        const PER_MSG_OVERHEAD: usize = 3;
        const REPLY_PRIMING: usize = 3;
        for msg in &req.messages {
            total += PER_MSG_OVERHEAD;
            total += encode_count(tokenizer, &msg.role)?;
            total += encode_count(tokenizer, &msg.content)?;
            for tc in &msg.tool_calls {
                total += tool_call_tokens(tokenizer, tc)?;
            }
        }
        total += REPLY_PRIMING;
    }

    if !req.raw_text.is_empty() {
        total += encode_count(tokenizer, &req.raw_text)?;
    }

    Ok(total)
}

fn tool_call_tokens(tokenizer: &Tokenizer, tc: &ToolCall) -> Result<usize, TokenizerError> {
    const TOOL_CALL_OVERHEAD: usize = 1;
    Ok(TOOL_CALL_OVERHEAD
        + encode_count(tokenizer, &tc.name)?
        + encode_count(tokenizer, &tc.arguments_json)?)
}

fn encode_count(tokenizer: &Tokenizer, text: &str) -> Result<usize, TokenizerError> {
    if text.is_empty() {
        return Ok(0);
    }
    // `false` add_special_tokens — we measure raw vocabulary tokens;
    // chat envelope is added by `count_tokens_anthropic` above.
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        tokenizer.encode(text, false)
    }));
    match result {
        Ok(Ok(enc)) => Ok(enc.get_ids().len()),
        Ok(Err(e)) => Err(TokenizerError::EncoderInternal {
            kind: "anthropic-v3-bpe",
            message: format!("tokenizers encode error: {e}"),
        }),
        Err(_) => Err(TokenizerError::EncoderInternal {
            kind: "anthropic-v3-bpe",
            message: "tokenizers encode panicked on input".to_string(),
        }),
    }
}

/// Layer A — sha256 of the embedded bytes against
/// [`crate::asset_sha256::ANTHROPIC_CLAUDE3`]. Constant-time compare
/// via `subtle::ConstantTimeEq` (same approach as SLICE_03 R2 m14).
fn verify_asset_sha256(
    encoder: &'static str,
    bytes: &[u8],
    expected: &'static str,
) -> Result<(), TokenizerError> {
    use subtle::ConstantTimeEq;

    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let actual_bytes: [u8; 32] = hasher.finalize().into();
    let actual_hex = hex::encode(actual_bytes);

    let expected_vec = match hex::decode(expected) {
        Ok(v) if v.len() == 32 => v,
        _ => {
            return Err(TokenizerError::AssetSignatureMismatch {
                encoder,
                expected,
                actual: format!("expected-const-malformed (got {actual_hex})"),
            });
        }
    };

    if actual_bytes.as_slice().ct_eq(&expected_vec).into() {
        Ok(())
    } else {
        Err(TokenizerError::AssetSignatureMismatch {
            encoder,
            expected,
            actual: actual_hex,
        })
    }
}

/// Layer B — runtime cross-check of the loaded tokenizer against the
/// hard-coded fixture vector (per spec §7.4.1).
fn cross_check(tokenizer: &Tokenizer, expected: &[u32]) -> Result<(), TokenizerError> {
    let enc = tokenizer
        .encode(CROSS_CHECK_FIXTURE, false)
        .map_err(|e| TokenizerError::AssetSignatureMismatch {
            encoder: "anthropic-claude3",
            expected: "cross_check_fixture_vector",
            actual: format!("fixture-encode-error: {e}"),
        })?;
    let actual = enc.get_ids();
    if actual != expected {
        let expected_summary: String = expected
            .iter()
            .take(6)
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(",");
        let actual_summary: String = actual
            .iter()
            .take(6)
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(",");
        return Err(TokenizerError::AssetSignatureMismatch {
            encoder: "anthropic-claude3",
            expected: "cross_check_fixture_vector",
            actual: format!(
                "fixture-vector-mismatch: expected first 6 tokens=[{expected_summary}], got=[{actual_summary}]"
            ),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Message;

    #[test]
    fn anthropic_loads_and_passes_integrity() {
        let _enc = AnthropicEncoder::new().expect("Anthropic encoder boots clean");
    }

    #[test]
    fn anthropic_kind_and_version_id() {
        let enc = AnthropicEncoder::new().expect("boot");
        assert_eq!(enc.kind(), EncoderKind::Anthropic);
        assert_eq!(enc.version_id(), ANTHROPIC_CLAUDE3_VERSION_ID);
        assert_eq!(enc.encoder_name(), "anthropic-v3-bpe");
    }

    #[test]
    fn anthropic_encodes_hello_world_to_2_tokens() {
        let enc = AnthropicEncoder::new().expect("boot");
        let req = TokenizeRequest {
            model: "claude-3-haiku".to_string(),
            raw_text: "hello world".to_string(),
            ..Default::default()
        };
        let r = enc.count_tokens_request(&req).unwrap();
        // Discovered count for this asset revision is 2.
        assert_eq!(r.input_tokens, 2);
        assert_eq!(r.kind, EncoderKind::Anthropic);
    }

    #[test]
    fn anthropic_chat_envelope_adds_overhead() {
        let enc = AnthropicEncoder::new().expect("boot");
        let raw_req = TokenizeRequest {
            model: "claude-3-haiku".to_string(),
            raw_text: "hello".to_string(),
            ..Default::default()
        };
        let chat_req = TokenizeRequest {
            model: "claude-3-haiku".to_string(),
            messages: vec![Message {
                role: "user".to_string(),
                content: "hello".to_string(),
                tool_calls: vec![],
            }],
            ..Default::default()
        };
        let raw_n = enc.count_tokens_request(&raw_req).unwrap().input_tokens;
        let chat_n = enc.count_tokens_request(&chat_req).unwrap().input_tokens;
        assert!(chat_n > raw_n, "chat ({chat_n}) should exceed raw ({raw_n})");
        // Envelope: 3 per-msg + role-tokens + content-tokens + 3 priming
        assert!(chat_n >= raw_n + 7);
    }

    #[test]
    fn anthropic_empty_request_is_0() {
        let enc = AnthropicEncoder::new().expect("boot");
        let req = TokenizeRequest::default();
        let r = enc.count_tokens_request(&req).unwrap();
        assert_eq!(r.input_tokens, 0);
    }

    #[test]
    fn anthropic_cross_check_pins_fixture_vector() {
        // Pin: if EXPECTED_ANTHROPIC_FIXTURE drifts away from what the
        // pinned tokenizer.json produces, boot fails — test asserts
        // the wrong-expected error surface (Layer B).
        let tokenizer = Tokenizer::from_bytes(ASSET_BYTES).expect("load");
        let bad: &[u32] = &[999, 999, 999];
        let err = cross_check(&tokenizer, bad).expect_err("Layer B must reject wrong expected");
        match err {
            TokenizerError::AssetSignatureMismatch { encoder, expected, .. } => {
                assert_eq!(encoder, "anthropic-claude3");
                assert_eq!(expected, "cross_check_fixture_vector");
            }
            other => panic!("expected AssetSignatureMismatch (Layer B), got {other:?}"),
        }
    }

    #[test]
    fn anthropic_layer_a_rejects_tampered_bytes() {
        // Pin: tampered bytes must fail sha256 (Layer A).
        let mut tampered = ASSET_BYTES.to_vec();
        if tampered.len() > 1024 {
            tampered[1024] ^= 0x01;
        }
        let err = verify_asset_sha256(
            "anthropic-claude3",
            &tampered,
            crate::asset_sha256::ANTHROPIC_CLAUDE3,
        )
        .expect_err("Layer A must reject tamper");
        match err {
            TokenizerError::AssetSignatureMismatch { encoder, .. } => {
                assert_eq!(encoder, "anthropic-claude3");
            }
            other => panic!("expected Layer A AssetSignatureMismatch, got {other:?}"),
        }
    }
}
