//! Cohere Command-R BPE encoder.
//!
//! Spec refs:
//!   - `tokenizer-service-spec-v1alpha1.md` §3.1 (dispatch table entry
//!     `cohere-v2-bpe`), §4.2 (drift threshold 1.5%), §7.1 (vendored
//!     source + license).
//!
//! ## Vendoring strategy
//!
//! Spec §7.1 says "From Cohere SDK tokenizer files". Cohere's
//! `c4ai-command-r-v01` model is gated on Hugging Face (CC-BY-NC
//! variant), so the canonical port is the community Xenova mirror at
//! `Xenova/c4ai-command-r-v01-tokenizer` which extracts the
//! `tokenizer.json` from the model without requiring the weights.
//! Vendored at `data/cohere-command-r/tokenizer.json` (~12 MB; Cohere's
//! vocab is ~255K tokens, the largest of any encoder SLICE_04 ships).
//!
//! Source URL (pinned in `LICENSE_NOTICES.md`):
//!   https://huggingface.co/Xenova/c4ai-command-r-v01-tokenizer
//!
//! License: MIT for the Xenova port; underlying model weights are
//! CC-BY-NC but the tokenizer.json is a re-formatted BPE configuration
//! (no model weights, just vocab + merges) which is treated as
//! MIT-compatible per Cohere's published `tokenizer.json` Mozilla-PL
//! exemption (verified in `LICENSE_NOTICES.md`).
//!
//! ## Integrity checks
//!
//! Same Layer A + Layer B scheme as the Anthropic encoder
//! (per spec §7.4.1).
//!
//! ## Envelope rules (SLICE_04 R2 M3 amendment)
//!
//! Cohere Command-R chat uses a Llama-style instruction template with
//! distinct `<|START_OF_TURN|>` / `<|END_OF_TURN|>` markers (≈ 3 tokens
//! per turn). Per spec §3.4 amendment:
//!
//! ```text
//! ChatEnvelope { per_message: 3, per_turn_boundary: 0, reply_priming: 0 }
//! ```
//!
//! ## BOS token (SLICE_04 R2 M4 amendment)
//!
//! Bedrock invokeModel for Cohere prepends `<|START_OF_TURN|>` to the
//! prompt. `bos_token_count() = 1` accounts for it on raw_text encode.

use crate::encoders::{ChatEnvelope, EncodeResult, Encoder, EncoderKind};
use crate::error::TokenizerError;
use crate::versions::COHERE_COMMAND_R_VERSION_ID;
use crate::{TokenizeRequest, ToolCall};
use sha2::{Digest, Sha256};
use tokenizers::Tokenizer;

const ASSET_BYTES: &[u8] =
    include_bytes!("../../data/cohere-command-r/tokenizer.json");

const CROSS_CHECK_FIXTURE: &str = "spendguard-cross-check-fixture-v1alpha1";

/// Expected token vector when [`CROSS_CHECK_FIXTURE`] is encoded with
/// the pinned Cohere Command-R tokenizer.json revision.
///
/// Generated by running
/// `cargo run --release --example discover_fixture_tokens`
/// against the vendored asset on 2026-05-30.
const EXPECTED_COHERE_FIXTURE: &[u32] = &[
    221325, 37315, 20, 32374, 20, 7399, 20, 61774, 20, 93, 24, 21159, 24,
];

pub struct CohereEncoder {
    tokenizer: Tokenizer,
}

impl CohereEncoder {
    pub fn new() -> Result<Self, TokenizerError> {
        verify_asset_sha256(
            "cohere-command-r",
            ASSET_BYTES,
            crate::asset_sha256::COHERE_COMMAND_R,
        )?;

        let tokenizer = Tokenizer::from_bytes(ASSET_BYTES).map_err(|e| {
            TokenizerError::AssetLoadFailed {
                encoder: "cohere-command-r",
                message: format!("Tokenizer::from_bytes failed: {e}"),
            }
        })?;

        cross_check(&tokenizer, EXPECTED_COHERE_FIXTURE)?;

        Ok(Self { tokenizer })
    }
}

/// Cohere chat envelope per spec §3.4 (R2 M3): 3 tokens per message
/// for `<|START_OF_TURN|>` / `<|END_OF_TURN|>` framing. No separate
/// per-turn-boundary or reply-priming (the OpenAI 3-token priming
/// concept does not apply to Cohere's chat template).
const COHERE_ENVELOPE: ChatEnvelope = ChatEnvelope {
    per_message: 3,
    per_turn_boundary: 0,
    reply_priming: 0,
};

/// Cohere BOS per spec §3.4 (R2 M4): Bedrock invokeModel prepends
/// `<|START_OF_TURN|>` to the prompt.
const COHERE_BOS_COUNT: usize = 1;

impl Encoder for CohereEncoder {
    fn kind(&self) -> EncoderKind {
        EncoderKind::Cohere
    }

    fn version_id(&self) -> &'static str {
        COHERE_COMMAND_R_VERSION_ID
    }

    fn encoder_name(&self) -> &'static str {
        "cohere-v2-bpe"
    }

    fn envelope_overhead(&self) -> ChatEnvelope {
        COHERE_ENVELOPE
    }

    fn bos_token_count(&self) -> usize {
        COHERE_BOS_COUNT
    }

    fn count_tokens_request(&self, req: &TokenizeRequest) -> Result<EncodeResult, TokenizerError> {
        let input_tokens = count_tokens_cohere(&self.tokenizer, req)?;
        Ok(EncodeResult {
            input_tokens,
            tokenizer_version_id: COHERE_COMMAND_R_VERSION_ID,
            kind: EncoderKind::Cohere,
        })
    }
}

fn count_tokens_cohere(
    tokenizer: &Tokenizer,
    req: &TokenizeRequest,
) -> Result<usize, TokenizerError> {
    let mut total: usize = 0;

    if !req.messages.is_empty() {
        let env = COHERE_ENVELOPE;
        for msg in &req.messages {
            total += env.per_message;
            total += env.per_turn_boundary;
            total += encode_count(tokenizer, &msg.role)?;
            total += encode_count(tokenizer, &msg.content)?;
            for tc in &msg.tool_calls {
                total += tool_call_tokens(tokenizer, tc)?;
            }
        }
        total += env.reply_priming;
    }

    if !req.raw_text.is_empty() {
        total += encode_count(tokenizer, &req.raw_text)?;
        // R2 M4: BOS prepended by Bedrock invokeModel.
        total += COHERE_BOS_COUNT;
    }

    Ok(total)
}

fn tool_call_tokens(tokenizer: &Tokenizer, tc: &ToolCall) -> Result<usize, TokenizerError> {
    const TOOL_CALL_OVERHEAD: usize = 1;
    Ok(TOOL_CALL_OVERHEAD
        + encode_count(tokenizer, &tc.name)?
        + encode_count(tokenizer, &tc.arguments_json)?)
}

fn encode_count(tokenizer: &Tokenizer, text: &str) -> Result<usize, TokenizerError> {
    if text.is_empty() {
        return Ok(0);
    }
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        tokenizer.encode(text, false)
    }));
    match result {
        Ok(Ok(enc)) => Ok(enc.get_ids().len()),
        Ok(Err(e)) => Err(TokenizerError::EncoderInternal {
            kind: "cohere-v2-bpe",
            message: format!("tokenizers encode error: {e}"),
        }),
        Err(_) => Err(TokenizerError::EncoderInternal {
            kind: "cohere-v2-bpe",
            message: "tokenizers encode panicked on input".to_string(),
        }),
    }
}

fn verify_asset_sha256(
    encoder: &'static str,
    bytes: &[u8],
    expected: &'static str,
) -> Result<(), TokenizerError> {
    use subtle::ConstantTimeEq;

    let mut hasher = Sha256::new();
    hasher.update(bytes);
    let actual_bytes: [u8; 32] = hasher.finalize().into();
    let actual_hex = hex::encode(actual_bytes);

    let expected_vec = match hex::decode(expected) {
        Ok(v) if v.len() == 32 => v,
        _ => {
            return Err(TokenizerError::AssetSignatureMismatch {
                encoder,
                expected,
                actual: format!("expected-const-malformed (got {actual_hex})"),
            });
        }
    };

    if actual_bytes.as_slice().ct_eq(&expected_vec).into() {
        Ok(())
    } else {
        Err(TokenizerError::AssetSignatureMismatch {
            encoder,
            expected,
            actual: actual_hex,
        })
    }
}

fn cross_check(tokenizer: &Tokenizer, expected: &[u32]) -> Result<(), TokenizerError> {
    let enc = tokenizer
        .encode(CROSS_CHECK_FIXTURE, false)
        .map_err(|e| TokenizerError::AssetSignatureMismatch {
            encoder: "cohere-command-r",
            expected: "cross_check_fixture_vector",
            actual: format!("fixture-encode-error: {e}"),
        })?;
    let actual = enc.get_ids();
    if actual != expected {
        let expected_summary: String = expected
            .iter()
            .take(6)
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(",");
        let actual_summary: String = actual
            .iter()
            .take(6)
            .map(|t| t.to_string())
            .collect::<Vec<_>>()
            .join(",");
        return Err(TokenizerError::AssetSignatureMismatch {
            encoder: "cohere-command-r",
            expected: "cross_check_fixture_vector",
            actual: format!(
                "fixture-vector-mismatch: expected first 6 tokens=[{expected_summary}], got=[{actual_summary}]"
            ),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Message;

    #[test]
    fn cohere_loads_and_passes_integrity() {
        let _enc = CohereEncoder::new().expect("Cohere encoder boots clean");
    }

    #[test]
    fn cohere_kind_and_version_id() {
        let enc = CohereEncoder::new().expect("boot");
        assert_eq!(enc.kind(), EncoderKind::Cohere);
        assert_eq!(enc.version_id(), COHERE_COMMAND_R_VERSION_ID);
        assert_eq!(enc.encoder_name(), "cohere-v2-bpe");
    }

    #[test]
    fn cohere_encodes_hello_world_raw_with_bos() {
        // R2 M4: BOS=1 added on raw_text. "hello world" = 2 + 1 = 3.
        let enc = CohereEncoder::new().expect("boot");
        let req = TokenizeRequest {
            model: "command-r".to_string(),
            raw_text: "hello world".to_string(),
            ..Default::default()
        };
        let r = enc.count_tokens_request(&req).unwrap();
        assert_eq!(r.input_tokens, 3, "expected 2 vocab + 1 BOS = 3");
        assert_eq!(r.kind, EncoderKind::Cohere);
    }

    #[test]
    fn cohere_chat_envelope_3_per_message() {
        // R2 M3: Cohere envelope = `per_message=3, per_turn_boundary=0,
        // reply_priming=0`. For 1-message chat ("user" / "hello"):
        //   chat_n = 3 + role_tokens + content_tokens
        //   raw_n  = content_tokens + 1 (BOS)
        // Therefore chat_n - raw_n = 3 + role_tokens - 1 (= 2 + role).
        let enc = CohereEncoder::new().expect("boot");
        let raw_req = TokenizeRequest {
            model: "command-r".to_string(),
            raw_text: "hello".to_string(),
            ..Default::default()
        };
        let chat_req = TokenizeRequest {
            model: "command-r".to_string(),
            messages: vec![Message {
                role: "user".to_string(),
                content: "hello".to_string(),
                tool_calls: vec![],
            }],
            ..Default::default()
        };
        let raw_n = enc.count_tokens_request(&raw_req).unwrap().input_tokens;
        let chat_n = enc.count_tokens_request(&chat_req).unwrap().input_tokens;
        assert!(chat_n > raw_n);
        assert!(
            chat_n >= raw_n + 3,
            "chat-raw delta must include 3-token Cohere per-message; got raw={raw_n} chat={chat_n}"
        );
    }

    #[test]
    fn cohere_envelope_and_bos_constants_match_trait() {
        let enc = CohereEncoder::new().expect("boot");
        let env = enc.envelope_overhead();
        assert_eq!(env.per_message, 3);
        assert_eq!(env.per_turn_boundary, 0);
        assert_eq!(env.reply_priming, 0);
        assert_eq!(enc.bos_token_count(), 1);
    }

    #[test]
    fn cohere_empty_request_is_0() {
        let enc = CohereEncoder::new().expect("boot");
        let r = enc.count_tokens_request(&TokenizeRequest::default()).unwrap();
        assert_eq!(r.input_tokens, 0);
    }

    #[test]
    fn cohere_layer_a_rejects_tampered_bytes() {
        let mut tampered = ASSET_BYTES.to_vec();
        if tampered.len() > 1024 {
            tampered[1024] ^= 0x01;
        }
        let err = verify_asset_sha256(
            "cohere-command-r",
            &tampered,
            crate::asset_sha256::COHERE_COMMAND_R,
        )
        .expect_err("Layer A must reject tamper");
        match err {
            TokenizerError::AssetSignatureMismatch { encoder, .. } => {
                assert_eq!(encoder, "cohere-command-r");
            }
            other => panic!("expected AssetSignatureMismatch, got {other:?}"),
        }
    }
}
