#!/usr/bin/env tsx
/**
 * D05 — TypeScript SDK proto codegen pipeline.
 *
 * Reads canonical proto sources from `proto/spendguard/` at the repo root and
 * writes deterministic, idempotent TypeScript output into
 * `sdk/typescript/src/_proto/` using the `@protobuf-ts/plugin` plugin
 * (locked decision: spec set §9.6 — chosen over `ts-proto` for stability).
 *
 * Slice spec: `docs/slices/COV_S05_02_d05_proto_codegen.md`.
 * Design refs: `docs/specs/coverage/D05_ts_sdk_substrate/design.md`
 *   §4.1 subpath table, §6.2 codegen, §7 codegen pipeline diagram,
 *   §9.6 locked plugin, §10 bundle budget (≤ 250 KB unminified).
 *
 * ## Usage
 *
 *   pnpm run proto:gen        # regenerate src/_proto/
 *   pnpm run proto:check      # CI gate: non-zero exit on any drift
 *
 * The check mode prints a unified diff of the first changed file so CI logs
 * surface the regression clearly rather than just `git diff --exit-code`.
 *
 * ## Determinism contract
 *
 * Running this script twice MUST produce byte-identical output. Because the
 * substrate ships the generated tree committed (operators install without a
 * `protoc` toolchain), any drift between proto sources and the committed tree
 * is a CI red. We enforce determinism by:
 *
 *   1. Sorting the input proto list lexicographically before invoking protoc.
 *   2. Pinning the `@protobuf-ts/plugin` version via `pnpm-lock.yaml`.
 *   3. Routing through a fresh tempdir so partial-write races cannot corrupt
 *      the committed tree on Ctrl-C.
 *   4. Normalising line endings to LF (matters on macOS / Linux dev mix).
 *   5. NOT emitting a wall-clock timestamp in any generated file. (The plugin
 *      does not by default; we assert post-generation that none crept in.)
 *
 * ## Anti-scope
 *
 * - No client code generation here (that ships in COV_S05_03).
 * - No barrel/index.ts hand-written file (that's COV_S05_03 too).
 * - No browser-targeted output (Node ESM only).
 */
import { spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// ── Paths ──────────────────────────────────────────────────────────────────

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

/** `sdk/typescript/` package root. */
const PKG_ROOT = resolve(__dirname, "..");

/** Repo root (two levels above `sdk/typescript/scripts/`). */
const REPO_ROOT = resolve(PKG_ROOT, "..", "..");

/** Canonical proto source — the ONLY input root per design §7. */
const PROTO_ROOT = resolve(REPO_ROOT, "proto");

/** Locked output tree per design §4.1 / acceptance gate. */
const OUT_DIR = resolve(PKG_ROOT, "src", "_proto");

/**
 * Protos generated by the TS SDK in v0.1.0 SLICE 02.
 *
 * Locked-in for this slice:
 *   - common:           shared types (Money, UUID, TraceContext, …) — required
 *                       by every downstream proto.
 *   - sidecar_adapter:  core adapter RPC surface (handshake, decision, …) —
 *                       the substrate's whole reason for existing.
 *   - tokenizer:        forward-reserved — adapters that pre-tokenize ship
 *                       the token count as a `ClaimEstimate.input_tokens`
 *                       hint; design §4.4 / implementation §3.1 barrel
 *                       imports the type.
 *
 * Deferred to a later slice (design §7 lists them but this slice cannot
 * include them without breaking the 250 KB unminified budget in §10 — see
 * `## Determinism contract → Budget deviation` below):
 *
 *   - ledger:                   only used by the demo webhook simulator;
 *                               production adapters never talk to the ledger
 *                               directly (Stage 2 §3.1). SLICE 03 will
 *                               decide whether to re-add it when wiring the
 *                               webhook simulator path, by which point a
 *                               trim of `force_optimize_code_size` deltas
 *                               can be measured against budget directly.
 *   - output_predictor_plugin:  optional for D08; will be added in the D08
 *                               slice that actually consumes it.
 *
 * Order matters for determinism: sorted lexicographically below before
 * invoking protoc so an accidental list reorder cannot reshuffle generated
 * file headers.
 */
const PROTO_FILES: readonly string[] = [
  "spendguard/common/v1/common.proto",
  "spendguard/sidecar_adapter/v1/adapter.proto",
  "spendguard/tokenizer/v1/tokenizer.proto",
];

/**
 * Plugin executable shipped by `@protobuf-ts/plugin`. The plugin registers
 * the `protoc-gen-ts` binary under `node_modules/.bin/`. We resolve it
 * explicitly rather than relying on `$PATH` so the script behaves the same
 * inside CI containers and on developer laptops.
 */
const PLUGIN_BIN = resolve(PKG_ROOT, "node_modules", ".bin", "protoc-gen-ts");

// ── CLI parsing ─────────────────────────────────────────────────────────────

interface CliOpts {
  check: boolean;
}

function parseArgs(argv: readonly string[]): CliOpts {
  const opts: CliOpts = { check: false };
  for (const a of argv) {
    if (a === "--check") opts.check = true;
    else if (a === "--help" || a === "-h") {
      printHelp();
      process.exit(0);
    } else {
      console.error(`proto.ts: unknown flag: ${a}`);
      printHelp();
      process.exit(2);
    }
  }
  return opts;
}

function printHelp(): void {
  console.error(
    [
      "Usage: pnpm run proto:gen | proto:check",
      "",
      "  (no flag)  Regenerate sdk/typescript/src/_proto/ from proto/spendguard/.",
      "  --check    Regenerate into a tempdir and exit non-zero on drift.",
      "             Used by CI to guard against forgotten codegen commits.",
    ].join("\n"),
  );
}

// ── Preflight ──────────────────────────────────────────────────────────────

function preflight(): void {
  if (!existsSync(PROTO_ROOT)) {
    fail(`canonical proto root not found at ${PROTO_ROOT}`);
  }
  for (const rel of PROTO_FILES) {
    const p = join(PROTO_ROOT, rel);
    if (!existsSync(p)) {
      fail(`proto input missing: ${p}`);
    }
  }
  if (!existsSync(PLUGIN_BIN)) {
    fail(
      [
        `@protobuf-ts/plugin binary not found at ${PLUGIN_BIN}.`,
        "Run `pnpm install` inside sdk/typescript first.",
      ].join("\n"),
    );
  }
  const probe = spawnSync("protoc", ["--version"], { encoding: "utf8" });
  if (probe.status !== 0) {
    fail(
      [
        "protoc not found on PATH.",
        "Install protoc (e.g. `brew install protobuf` on macOS, `apt-get install protobuf-compiler` on Debian/Ubuntu).",
        "Minimum tested version: libprotoc 27 (we test against 35).",
      ].join("\n"),
    );
  }
}

// ── Codegen ────────────────────────────────────────────────────────────────

/**
 * Invoke `protoc` with `@protobuf-ts/plugin` and write the tree under `dest`.
 *
 * Plugin parameters chosen for determinism + TS ergonomics:
 *   - `long_type_string`: render `int64` / `uint64` as JS strings (we never
 *     send raw bigints over UDS; design §4.3 uses decimal strings for
 *     NUMERIC(38,0) money). Without this, generated code uses `bigint` which
 *     breaks JSON serialisation in customer adapter code.
 *   - `force_server_none`: skip server stubs we don't need (the SDK is a
 *     pure client; sidecar implements the server side in Rust).
 *   - `ts_nocheck`: prepend `// @ts-nocheck` to silence noUncheckedIndexedAccess
 *     pedantry inside generated files (only). User-authored code in `src/`
 *     keeps full strict mode.
 *   - `force_optimize_code_size`: tilt the generated reflection-info encoding
 *     toward smaller output. Helps stay under the 250 KB budget when more
 *     proto files are added without bumping the runtime path.
 *
 * Flags intentionally NOT set:
 *   - `generate_dependencies`: leave default. The plugin auto-generates the
 *     Google well-known types (`google/protobuf/timestamp.ts`,
 *     `google/protobuf/struct.ts`) when imported by our protos — that path is
 *     unavoidable because the runtime ships the read/write codec but not the
 *     concrete `MessageType<Timestamp>` reflection wrappers our generated
 *     code needs at runtime. The well-known tree adds < 20 KB combined and
 *     still leaves > 230 KB of budget headroom.
 *   - `eslint_disable`: leave default (off). The substrate uses biome, not
 *     eslint; biome ignores `_proto/` once COV_S05_03 wires the lint config.
 *   - `client_grpc1`: leave default (generic client). The generic client is
 *     dispatcher-agnostic and binds to `@protobuf-ts/grpc-transport` per
 *     design §4 / `implementation.md` §4 (`new SidecarAdapterClient(transport)`).
 *     `client_grpc1` would lock the client to raw @grpc/grpc-js and bypass
 *     the grpc-transport's deadline/metadata helpers we rely on.
 */
function runProtoc(dest: string): void {
  mkdirSync(dest, { recursive: true });

  const params = [
    "long_type_string",
    "force_server_none",
    "ts_nocheck",
    "force_optimize_code_size",
  ].join(",");

  // Sort inputs deterministically. PROTO_FILES is already sorted; this is a
  // belt-and-braces guard against future edits that forget the convention.
  const inputs = [...PROTO_FILES].sort();

  const args: string[] = [
    `--proto_path=${PROTO_ROOT}`,
    `--plugin=protoc-gen-ts=${PLUGIN_BIN}`,
    `--ts_out=${params}:${dest}`,
    ...inputs,
  ];

  // Pin LC_ALL / LANG / SOURCE_DATE_EPOCH for deterministic sort + zero clock
  // leakage. The plugin itself does not stamp timestamps, but a future plugin
  // bump that adds one would be caught by --check.
  const env = {
    ...process.env,
    LC_ALL: "C",
    LANG: "C",
    SOURCE_DATE_EPOCH: "0",
  };

  const res = spawnSync("protoc", args, {
    cwd: PROTO_ROOT,
    env,
    stdio: ["ignore", "inherit", "inherit"],
  });
  if (res.status !== 0) {
    fail(`protoc exited with status ${res.status ?? "<signal>"}`);
  }

  postProcess(dest);
}

/**
 * Normalise generated output for cross-platform reproducibility.
 *
 *   - Force LF line endings (macOS / Linux dev mix could otherwise drift via
 *     a misconfigured editor; protoc itself emits LF on POSIX).
 *   - Assert no wall-clock-looking strings crept into headers. Cheap regex
 *     check — if a future plugin version stamps the build time, we fail loud
 *     in --check rather than silently breaking idempotency.
 */
function postProcess(dest: string): void {
  for (const file of walkTs(dest)) {
    const raw = readFileSync(file, "utf8");
    const normalised = raw.replace(/\r\n/g, "\n");
    if (normalised !== raw) {
      writeFileSync(file, normalised, "utf8");
    }
    assertNoTimestampStamp(file, normalised);
  }
}

function assertNoTimestampStamp(file: string, contents: string): void {
  // Build-time wall-clock leakage check, scoped to the plugin's `@generated by`
  // header line only. That's the natural place a plugin would stamp the build
  // time; deeper in the file, ISO-8601-looking strings are legitimate JSDoc
  // examples (e.g. google/protobuf/Timestamp documents its range using
  // "0001-01-01T00:00:00Z" / "9999-12-31T23:59:59.999999999Z").
  //
  // protobuf-ts 2.11.1 emits a header with the plugin version + params but
  // no wall clock. If a future version adds one, --check will catch the
  // drift, but this assertion gives a more pointed message.
  const firstLine = contents.split("\n", 1)[0] ?? "";
  const buildStamp = /\b20\d{2}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/;
  if (buildStamp.test(firstLine)) {
    fail(
      [
        `${relative(PKG_ROOT, file)} contains a current-era timestamp in its plugin header.`,
        "This breaks deterministic codegen. Pin or downgrade @protobuf-ts/plugin.",
      ].join("\n"),
    );
  }
}

function* walkTs(root: string): Generator<string> {
  if (!existsSync(root)) return;
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const p = join(root, entry.name);
    if (entry.isDirectory()) {
      yield* walkTs(p);
    } else if (entry.isFile() && p.endsWith(".ts")) {
      yield p;
    }
  }
}

// ── Modes ──────────────────────────────────────────────────────────────────

function gen(): void {
  // Clean atomically: generate into a tempdir, then swap. This avoids leaving
  // a half-rendered tree if protoc dies mid-flight.
  const staging = mkdtempSync(join(tmpdir(), "spendguard-proto-gen-"));
  try {
    runProtoc(staging);
    if (existsSync(OUT_DIR)) {
      rmSync(OUT_DIR, { recursive: true, force: true });
    }
    mkdirSync(OUT_DIR, { recursive: true });
    // cpSync with `recursive: true` preserves directory structure but not
    // timestamps — exactly what we want for byte-stable git diffs.
    for (const entry of readdirSync(staging)) {
      cpSync(join(staging, entry), join(OUT_DIR, entry), { recursive: true });
    }
    reportSize();
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

function check(): void {
  const staging = mkdtempSync(join(tmpdir(), "spendguard-proto-check-"));
  try {
    runProtoc(staging);
    const drift = diffTrees(OUT_DIR, staging);
    if (drift.length === 0) {
      console.log("proto:check OK — committed tree matches `proto:gen` output.");
      return;
    }
    console.error(
      [
        "",
        "proto:check FAILED — committed tree drifts from canonical proto sources.",
        "",
        "Run `pnpm --filter @spendguard/sdk run proto:gen` and commit the result.",
        "",
        "Drifted entries:",
        ...drift.map((d) => `  - ${d}`),
        "",
      ].join("\n"),
    );
    process.exitCode = 1;
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}

/**
 * Walk both trees, compare files by byte content. Returns relative paths of
 * any drifted, added, or removed entries (sorted).
 */
function diffTrees(committed: string, fresh: string): string[] {
  const cMap = new Map<string, Buffer>();
  const fMap = new Map<string, Buffer>();
  const drift: string[] = [];

  if (existsSync(committed)) {
    for (const file of walkTs(committed)) {
      cMap.set(relative(committed, file), readFileSync(file));
    }
  }
  if (existsSync(fresh)) {
    for (const file of walkTs(fresh)) {
      fMap.set(relative(fresh, file), readFileSync(file));
    }
  }

  const keys = new Set<string>([...cMap.keys(), ...fMap.keys()]);
  for (const k of [...keys].sort()) {
    const c = cMap.get(k);
    const f = fMap.get(k);
    if (!c) drift.push(`added (missing from committed tree): ${k}`);
    else if (!f) drift.push(`removed (extra in committed tree): ${k}`);
    else if (!c.equals(f)) drift.push(`modified: ${k}`);
  }
  return drift;
}

/**
 * Report generated tree size and HARD-FAIL when over the 250 KB unminified
 * budget from design §10. R2 fix per R1 review M2: prior JSDoc claimed
 * "warn (not fail)" but the body always called `fail()` — comment now
 * matches behaviour. The hard fail here means a SLICE 3+ proto add
 * cannot ship without a deliberate budget reckoning. COV_S05_10 will add
 * an additional minified-bundle hard fail (`pnpm run size`).
 */
function reportSize(): void {
  const totalBytes = treeSize(OUT_DIR);
  const kb = (totalBytes / 1024).toFixed(1);
  const budgetBytes = 250 * 1024;
  const headroom = budgetBytes - totalBytes;
  const headroomKb = (headroom / 1024).toFixed(1);
  console.log(`proto:gen OK — generated ${kb} KB (budget 250 KB, headroom ${headroomKb} KB).`);
  if (totalBytes > budgetBytes) {
    fail(
      `generated tree (${kb} KB) exceeds 250 KB budget (design §10). Trim before committing.`,
    );
  }
}

function treeSize(root: string): number {
  if (!existsSync(root)) return 0;
  let total = 0;
  for (const entry of readdirSync(root, { withFileTypes: true })) {
    const p = join(root, entry.name);
    if (entry.isDirectory()) {
      total += treeSize(p);
    } else if (entry.isFile()) {
      total += statSync(p).size;
    }
  }
  return total;
}

// ── Error handling ─────────────────────────────────────────────────────────

function fail(message: string): never {
  console.error(`proto.ts: ${message}`);
  process.exit(1);
}

// ── Entry point ────────────────────────────────────────────────────────────

const opts = parseArgs(process.argv.slice(2));
preflight();
if (opts.check) {
  check();
} else {
  gen();
}
