//! Cross-language byte-equivalence test.
//!
//! Per `docs/specs/auto-instrument-egress-proxy-spec.md` v7 §15 row 2:
//! the load-bearing contract for the `spendguard-ids` crate is that the
//! Rust port produces the same UUIDs as the Python helper
//! (`sdk/python/src/spendguard/ids.py:161-173`) for every (signature,
//! scope) pair.
//!
//! Fixture at `tests/fixtures/python_v1.json` is generated by running
//! the Python helper over a hand-curated input set (including UTF-8,
//! empty strings, separator-collision edge cases) and writing the
//! resulting UUIDs verbatim. CI runs this test on every PR touching
//! either `sdk/python/src/spendguard/ids.py` or `services/ids/`.
//!
//! When the algorithm intentionally changes, both the Python helper
//! and the fixture file must be updated in lockstep (and the fixture
//! filename bumps from `python_v1.json` → `python_v2.json`).

use serde::Deserialize;
use spendguard_ids::derive_uuid_from_signature;

#[derive(Debug, Deserialize)]
struct FixtureRow {
    signature: String,
    scope: String,
    expected_uuid: String,
}

#[test]
fn rust_uuids_match_python_oracle() {
    let raw = std::fs::read_to_string("tests/fixtures/python_v1.json")
        .expect("read fixture (run from services/ids/ working directory)");
    let rows: Vec<FixtureRow> = serde_json::from_str(&raw).expect("parse fixture JSON");
    assert!(rows.len() >= 10, "fixture is too small to be a real oracle");

    let mut mismatches = Vec::new();
    for (i, row) in rows.iter().enumerate() {
        let got = derive_uuid_from_signature(&row.signature, &row.scope);
        if got.to_string() != row.expected_uuid {
            mismatches.push(format!(
                "[{}] sig={:?} scope={:?}: expected {} got {}",
                i, row.signature, row.scope, row.expected_uuid, got
            ));
        }
    }

    if !mismatches.is_empty() {
        panic!(
            "Cross-language byte-equivalence FAILED on {} of {} fixture rows:\n{}",
            mismatches.len(),
            rows.len(),
            mismatches.join("\n")
        );
    }
}

#[test]
fn separator_prevents_collision_class() {
    // The no-separator implementation would let
    // ("Xabc", "scope1") collide with ("abc", "scope1X").
    // Verify the separator is in place by checking these specific
    // pairs produce DIFFERENT UUIDs.
    let a = derive_uuid_from_signature("Xabc", "scope1");
    let b = derive_uuid_from_signature("abc", "scope1X");
    assert_ne!(
        a, b,
        "collision class — separator missing in derive_uuid_from_signature"
    );
}
