//! Regenerate the synthetic `.cursor-rpc` fixture corpus.
//!
//! D17 SLICE 8 ([`design.md`](../docs/specs/coverage/D17_cursor_mitm/design.md)
//! §7): the codec's fixture corpus is reproducible from a Rust
//! generator so reviewers can re-derive every byte of every fixture
//! without trusting opaque blobs.
//!
//! Usage:
//!
//! ```sh
//! cargo run --manifest-path services/cursor_codec/Cargo.toml \
//!     --example regenerate_fixtures
//! ```
//!
//! Each fixture is written under `services/cursor_codec/fixtures/synthetic/`
//! plus a sidecar `.manifest.json` with capture date, version range,
//! and field-by-field hex evidence per `review-standards.md` §2 (R2,
//! R4). Existing SLICE 1 fixtures (`synthetic_unary_v1.cursor-rpc`,
//! `synthetic_streaming_chunked_v1.cursor-rpc`) are intentionally
//! NOT touched by this binary — they were generated by the SLICE 2
//! framing tests and are committed verbatim. This binary owns the
//! NEW SLICE 8 fixtures only.

use std::path::PathBuf;

use bytes::Bytes;
use spendguard_cursor_codec::cursor_proto::{
    CursorChatRequest, CursorChatResponseChunk, Message as CursorMessage,
};
use spendguard_cursor_codec::{
    request_frame, response_chunk_frame, trailers_frame, write_fixture_bytes, FixtureFrame,
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("fixtures/synthetic");
    std::fs::create_dir_all(&out_dir)?;

    let mut total_bytes = 0usize;

    for (name, frames, manifest) in fixtures() {
        let bytes = write_fixture_bytes(&frames);
        if bytes.len() > 64 * 1024 {
            return Err(format!(
                "fixture {name} is {} bytes (cap is 64 KiB per review-standards.md C4)",
                bytes.len()
            )
            .into());
        }
        let fixture_path = out_dir.join(format!("{name}.cursor-rpc"));
        let manifest_path = out_dir.join(format!("{name}.cursor-rpc.manifest.json"));
        std::fs::write(&fixture_path, &bytes)?;
        std::fs::write(&manifest_path, manifest)?;
        total_bytes += bytes.len();
        println!(
            "[regenerate_fixtures] wrote {name} ({} bytes, {} frames)",
            bytes.len(),
            frames.len()
        );
    }

    println!("[regenerate_fixtures] DONE — total {total_bytes} bytes across new fixtures");
    Ok(())
}

fn fixtures() -> Vec<(&'static str, Vec<FixtureFrame>, &'static str)> {
    vec![
        (
            "synthetic_multiturn_v1",
            multiturn_fixture(),
            MULTITURN_MANIFEST,
        ),
        (
            "synthetic_tool_calls_v1",
            tool_calls_fixture(),
            TOOL_CALLS_MANIFEST,
        ),
        (
            "synthetic_error_response_v1",
            error_response_fixture(),
            ERROR_MANIFEST,
        ),
        (
            "synthetic_long_stream_v1",
            long_stream_fixture(),
            LONG_STREAM_MANIFEST,
        ),
    ]
}

// ============================================================================
// (1) Multi-turn conversation
// ============================================================================
//
// Three-turn Cursor Agent session: system + user + assistant + user
// followup. Request frame carries the full history; response stream
// emits a 3-chunk reply ending with finish_reason="stop".

fn multiturn_fixture() -> Vec<FixtureFrame> {
    let req = CursorChatRequest {
        messages: vec![
            CursorMessage {
                role: "system".to_string(),
                content: "You are Cursor Agent. Be terse.".to_string(),
            },
            CursorMessage {
                role: "user".to_string(),
                content: "explain reservation".to_string(),
            },
            CursorMessage {
                role: "assistant".to_string(),
                content: "A pre-call hold on a budget.".to_string(),
            },
            CursorMessage {
                role: "user".to_string(),
                content: "what about release?".to_string(),
            },
        ],
        model: "claude-3.5-sonnet".to_string(),
        system: Some("You are Cursor Agent. Be terse.".to_string()),
        max_tokens: Some(256),
        temperature: Some(0.2),
    };

    let chunk1 = chunk("claude-3.5-sonnet", "Release ", None, None);
    let chunk2 = chunk("", "refunds the ", None, None);
    let chunk3 = chunk("", "hold.", Some("stop"), Some(11));
    let trailers = Bytes::from_static(b"grpc-status:0");

    vec![
        request_frame(1_716_000_000_000, &req),
        response_chunk_frame(1_716_000_000_020, &chunk1, 0x00),
        response_chunk_frame(1_716_000_000_040, &chunk2, 0x00),
        response_chunk_frame(1_716_000_000_060, &chunk3, 0x00),
        trailers_frame(1_716_000_000_080, trailers),
    ]
}

const MULTITURN_MANIFEST: &str = r#"{
  "fixture": "synthetic_multiturn_v1.cursor-rpc",
  "kind": "synthetic",
  "cursor_min_version": "synthetic",
  "cursor_max_version": "synthetic",
  "captured_utc": "2026-06-07T00:00:00Z",
  "frames": 5,
  "shape": "multi-turn conversation (4 messages: system+user+assistant+user) + 3-chunk streaming response + EOS trailers (grpc-status:0)",
  "field_evidence": [
    {"field": "messages", "tag": 1, "wire_type": "length-delimited", "evidence": "4 repeated Message entries; first role=system asserts CursorChatRequest.system precedence rule (translator drops top-level system when leading messages entry is role=system)"},
    {"field": "model", "tag": 2, "wire_type": "length-delimited", "evidence": "claude-3.5-sonnet"},
    {"field": "system", "tag": 3, "wire_type": "length-delimited", "evidence": "same string as messages[0].content; translator drops"},
    {"field": "max_tokens", "tag": 4, "wire_type": "varint", "evidence": "256"},
    {"field": "temperature", "tag": 5, "wire_type": "fixed32", "evidence": "0.2"}
  ],
  "expected_replay_report": {
    "request_frames_decoded": 1,
    "response_chunks_decoded": 3,
    "end_of_stream_frames": 1,
    "finish_reason": "stop",
    "cumulative_output_tokens": 11,
    "sidecar_reserve_calls": 1,
    "sidecar_commit_calls": 1,
    "upstream_error": false,
    "all_frames_round_trip": true
  },
  "review_standards_refs": ["W1", "W3", "W5", "C1", "C4", "R4"]
}
"#;

// ============================================================================
// (2) Tool calls (Cursor Agent mode)
// ============================================================================
//
// Cursor Agent mode embeds tool calls as messages with role="tool" and
// content carrying a JSON payload representing the tool result. The
// envelope shape used here is the SpendGuard placeholder shape (string
// content), but the content body is the tool-call JSON Cursor
// observably emits.

fn tool_calls_fixture() -> Vec<FixtureFrame> {
    let req = CursorChatRequest {
        messages: vec![
            CursorMessage {
                role: "user".to_string(),
                content: "what does file_search return for tokenizer".to_string(),
            },
            CursorMessage {
                role: "assistant".to_string(),
                content: r#"{"tool_calls":[{"id":"call_01","type":"function","function":{"name":"file_search","arguments":"{\"query\":\"tokenizer\"}"}}]}"#.to_string(),
            },
            CursorMessage {
                role: "tool".to_string(),
                content: r#"{"tool_call_id":"call_01","name":"file_search","content":"services/tokenizer/src/lib.rs"}"#.to_string(),
            },
        ],
        model: "gpt-4o".to_string(),
        system: None,
        max_tokens: Some(512),
        temperature: Some(0.0),
    };

    // Two response chunks then a tool_calls-flavoured finish.
    let chunk1 = chunk("gpt-4o", "Found ", None, None);
    let chunk2 = chunk("", "match.", Some("tool_calls"), Some(2));
    let trailers = Bytes::from_static(b"grpc-status:0");

    vec![
        request_frame(1_716_000_001_000, &req),
        response_chunk_frame(1_716_000_001_010, &chunk1, 0x00),
        response_chunk_frame(1_716_000_001_020, &chunk2, 0x00),
        trailers_frame(1_716_000_001_030, trailers),
    ]
}

const TOOL_CALLS_MANIFEST: &str = r#"{
  "fixture": "synthetic_tool_calls_v1.cursor-rpc",
  "kind": "synthetic",
  "cursor_min_version": "synthetic",
  "cursor_max_version": "synthetic",
  "captured_utc": "2026-06-07T00:00:00Z",
  "frames": 4,
  "shape": "Cursor Agent mode tool-call session: user prompt + assistant tool_calls envelope + tool result message; response stream ends with finish_reason=tool_calls (NOT stop)",
  "field_evidence": [
    {"field": "messages[1].content", "evidence": "carries Cursor-observed tool_calls JSON shape inline in the placeholder string content field (per RECON.md §2.2 the wire is still UTF-8 string today)"},
    {"field": "messages[2].role", "evidence": "tool — exercises the role vocabulary beyond user|assistant|system"},
    {"field": "model", "evidence": "gpt-4o (Cursor labels both gpt-4o and claude-3.5-sonnet directly in capture)"},
    {"field": "CursorChatResponseChunk.finish_reason", "evidence": "tool_calls (not stop) — translator must NOT mis-classify as a normal completion"}
  ],
  "expected_replay_report": {
    "request_frames_decoded": 1,
    "response_chunks_decoded": 2,
    "end_of_stream_frames": 1,
    "finish_reason": "tool_calls",
    "cumulative_output_tokens": 2,
    "sidecar_reserve_calls": 1,
    "sidecar_commit_calls": 1,
    "upstream_error": false,
    "all_frames_round_trip": true
  },
  "review_standards_refs": ["W1", "W3", "W5", "C1", "C4", "R4"]
}
"#;

// ============================================================================
// (3) Error responses
// ============================================================================
//
// Cursor's wire surfaces upstream LLM-side errors as Connect-RPC
// trailers with grpc-status > 0 and grpc-message carrying a human
// string. The codec's release-and-pass-through contract per design.md
// §2 means the replay harness MUST detect this and short-circuit the
// commit path.

fn error_response_fixture() -> Vec<FixtureFrame> {
    let req = CursorChatRequest {
        messages: vec![CursorMessage {
            role: "user".to_string(),
            content: "trigger an upstream error".to_string(),
        }],
        model: "gpt-4o-mini".to_string(),
        system: None,
        max_tokens: Some(64),
        temperature: Some(0.0),
    };

    // No data frames — straight to trailers with grpc-status:13
    // (gRPC INTERNAL).
    let trailers =
        Bytes::from_static(b"grpc-status:13\rgrpc-message:upstream provider returned 500");

    vec![
        request_frame(1_716_000_002_000, &req),
        trailers_frame(1_716_000_002_005, trailers),
    ]
}

const ERROR_MANIFEST: &str = r#"{
  "fixture": "synthetic_error_response_v1.cursor-rpc",
  "kind": "synthetic",
  "cursor_min_version": "synthetic",
  "cursor_max_version": "synthetic",
  "captured_utc": "2026-06-07T00:00:00Z",
  "frames": 2,
  "shape": "Cursor request + immediate trailers frame with grpc-status:13 (gRPC INTERNAL); NO response data chunks",
  "field_evidence": [
    {"field": "trailers.payload", "evidence": "grpc-status:13\\rgrpc-message:upstream provider returned 500"},
    {"field": "Frame.flags", "evidence": "0x02 on the trailers frame — review-standards W3 (end-of-stream detected without optimistic data decode)"}
  ],
  "expected_replay_report": {
    "request_frames_decoded": 1,
    "response_chunks_decoded": 0,
    "end_of_stream_frames": 1,
    "finish_reason": null,
    "cumulative_output_tokens": null,
    "sidecar_reserve_calls": 1,
    "sidecar_commit_calls": 0,
    "upstream_error": true,
    "all_frames_round_trip": true
  },
  "review_standards_refs": ["W1", "W3", "W5", "P3", "C1", "C4", "R4"]
}
"#;

// ============================================================================
// (4) Long stream (≥10 chunks)
// ============================================================================
//
// A 12-chunk streaming response. Mirrors a long-form Cursor Agent
// reply. Each chunk carries cumulative_output_tokens so the replay
// harness can track per-chunk token deltas.

fn long_stream_fixture() -> Vec<FixtureFrame> {
    let req = CursorChatRequest {
        messages: vec![CursorMessage {
            role: "user".to_string(),
            content: "stream a long answer".to_string(),
        }],
        model: "claude-3.5-sonnet".to_string(),
        system: None,
        max_tokens: Some(1024),
        temperature: Some(0.3),
    };

    let mut frames = vec![request_frame(1_716_000_003_000, &req)];

    // Twelve content chunks then a terminal finish chunk + trailers.
    let deltas = [
        "Once ",
        "upon ",
        "a ",
        "time ",
        "there ",
        "was ",
        "a ",
        "budget ",
        "that ",
        "always ",
        "balanced ",
        "perfectly.",
    ];
    let mut cumulative = 0u32;
    for (i, delta) in deltas.iter().enumerate() {
        // Tokens-per-chunk is delta-length / 4 floored to 1 — same
        // chars/4 heuristic the rest of the codec falls back to.
        let tokens = ((delta.len() as u32) / 4).max(1);
        cumulative += tokens;
        let model = if i == 0 { "claude-3.5-sonnet" } else { "" };
        let c = chunk(model, delta, None, Some(cumulative));
        frames.push(response_chunk_frame(
            1_716_000_003_000 + 10 + (i as u64) * 5,
            &c,
            0x00,
        ));
    }
    // Terminal data chunk: empty delta, finish_reason=stop.
    let terminal = chunk("", "", Some("stop"), Some(cumulative));
    frames.push(response_chunk_frame(
        1_716_000_003_000 + 10 + (deltas.len() as u64) * 5,
        &terminal,
        0x00,
    ));
    frames.push(trailers_frame(
        1_716_000_003_000 + 20 + (deltas.len() as u64) * 5,
        Bytes::from_static(b"grpc-status:0"),
    ));
    frames
}

const LONG_STREAM_MANIFEST: &str = r#"{
  "fixture": "synthetic_long_stream_v1.cursor-rpc",
  "kind": "synthetic",
  "cursor_min_version": "synthetic",
  "cursor_max_version": "synthetic",
  "captured_utc": "2026-06-07T00:00:00Z",
  "frames": 15,
  "shape": "1 request + 12 streaming content chunks + 1 terminal finish chunk (finish_reason=stop) + 1 EOS trailers (grpc-status:0)",
  "field_evidence": [
    {"field": "CursorChatResponseChunk.cumulative_output_tokens", "evidence": "monotonically increasing across chunks; terminal chunk repeats the final value"},
    {"field": "CursorChatResponseChunk.model", "evidence": "stamped only on the first content chunk; empty on follow-ups (RECON.md §3 observation)"},
    {"field": "frames_read", "evidence": "13 data frames + 1 EOS = 14 frame records; envelope_count=15 includes the 1 request frame"}
  ],
  "expected_replay_report": {
    "request_frames_decoded": 1,
    "response_chunks_decoded": 13,
    "end_of_stream_frames": 1,
    "finish_reason": "stop",
    "sidecar_reserve_calls": 1,
    "sidecar_commit_calls": 1,
    "upstream_error": false,
    "all_frames_round_trip": true
  },
  "review_standards_refs": ["W1", "W3", "W5", "C1", "C4", "R4"]
}
"#;

fn chunk(
    model: &str,
    delta: &str,
    finish_reason: Option<&str>,
    cumulative_output_tokens: Option<u32>,
) -> CursorChatResponseChunk {
    CursorChatResponseChunk {
        model: model.to_string(),
        delta: delta.to_string(),
        finish_reason: finish_reason.map(|s| s.to_string()),
        cumulative_output_tokens,
    }
}
