// SpendGuard SDK — generated proto barrel.
//
// Re-exports namespaces from `_proto/spendguard/**` so customers can `import
// { adapter, common, tokenizer } from "@spendguard/sdk/proto"`. The shape
// mirrors the Python `sdk/python/src/spendguard/_proto/` package.
//
// The leaf modules under `_proto/` are committed (not gitignored) and are
// regenerated by `pnpm run proto`. Hand-edits there are forbidden; this
// barrel lives outside `_proto/` so the `proto:check` drift gate does not
// see it as drift (the script walks every `.ts` file under `_proto/`).
//
// **Intentional omission — `ledger`.** SLICE 2 (`COV_S05_02_d05_proto_codegen`)
// deferred `ledger.proto` codegen as deviation #1 because no v0.1.x adapter
// requires the ledger namespace directly — the sidecar adapter wraps the
// ledger interactions and adapters consume `SpendGuardClient.release()` /
// `commitEstimated()` instead of the raw ledger RPCs. A future slice (TBD,
// tracked as a follow-up issue) will add `ledger` and `output_predictor_plugin`
// once a downstream deliverable needs them. The barrel will then gain a
// `ledger` export without a v0.minor bump because this is an additive change.

export * as common from "./_proto/spendguard/common/v1/common.js";
export * as adapter from "./_proto/spendguard/sidecar_adapter/v1/adapter.js";
export * as adapterClient from "./_proto/spendguard/sidecar_adapter/v1/adapter.client.js";
export * as tokenizer from "./_proto/spendguard/tokenizer/v1/tokenizer.js";
export * as tokenizerClient from "./_proto/spendguard/tokenizer/v1/tokenizer.client.js";
