// @spendguard/botpress-integration — runtime entry point + public barrel.
//
// Default export: a Botpress `Integration` instance (typed against the
// generated `.botpress` codegen) implementing the LLM-provider actions
// `generateContent` (the SpendGuard gate point) and `listLanguageModels`.
// `bp build` / `bp deploy` consumes this default export as the integration
// implementation; the Botpress runtime invokes `actions.generateContent`
// whenever a bot needs an LLM completion.
//
// Named exports surface the typed helpers + error classes consumers may want
// to introspect (testing, decoration, custom error handling).
//
// `.botpress` is generated by `bp build` (offline, no auth) from
// `integration.definition.ts`. The CI workflow runs `bp build` before
// Typecheck so the import resolves.

import { validateConfiguration } from "./lifecycle/validateConfiguration.js";
import { runGenerateContent } from "./llm/generateContent.js";
import { toInterfaceOutput, toInternalInput } from "./llm/interfaceAdapter.js";
import { runListLanguageModels } from "./llm/listLanguageModels.js";
import * as bp from ".botpress";

// ── Public surface — named exports ────────────────────────────────────

export { VERSION } from "./version.js";
export { ConfigurationSchema, ConfigurationObjectSchema, SpendGuardConfigError } from "./config.js";
export type { Configuration } from "./config.js";
export {
  SpendGuardReservation,
  DecisionDenied,
  SidecarUnavailable,
} from "./reservation.js";
export type {
  BotpressCallContext,
  ReservationHandle,
} from "./reservation.js";
export {
  toBindingFromActionInput,
  pickTenantId,
  resolveModel,
  resolveMaxTokens,
} from "./adapter/binding.js";
export type { BotpressActionCtx } from "./adapter/binding.js";
export { toRuntimeError, runtimeErrorCode, codeFor } from "./adapter/errors.js";
export type { SpendGuardCode } from "./adapter/errors.js";
export {
  defaultForward,
  ProviderForwardError,
  toForwardRequest,
  toGenerateContentOutput,
} from "./provider/forward.js";
export type { ForwardFn, ForwardRequest, ForwardResult } from "./provider/forward.js";
export { runGenerateContent } from "./llm/generateContent.js";
export type { GenerateContentArgs, MinimalLogger } from "./llm/generateContent.js";
export { runListLanguageModels } from "./llm/listLanguageModels.js";
export {
  flattenContent,
  toInterfaceOutput,
  toInternalInput,
} from "./llm/interfaceAdapter.js";
export type {
  InterfaceGenerateContentInput,
  InterfaceGenerateContentOutput,
} from "./llm/interfaceAdapter.js";
export * as llmSchemas from "./llm/schemas.js";
export { validateConfiguration } from "./lifecycle/validateConfiguration.js";

// ── Default export — the Botpress Integration instance ────────────────

export default new bp.Integration({
  // INV-4: prove the SpendGuard sidecar wiring at install time with a
  // 1-token reserve + release roundtrip. A bad sidecar URL / mTLS material /
  // budget id fails the install rather than the first conversation.
  register: async ({ ctx }) => {
    await validateConfiguration({ configuration: ctx.configuration });
  },
  unregister: async () => {
    // No durable per-install state to tear down — the SpendGuard reservation
    // lifecycle is per-call.
  },
  channels: {},
  // No webhook surface: SpendGuard is invoked synchronously via actions.
  handler: async () => {},
  actions: {
    // The SpendGuard gate point. Reserve -> forward -> commit (fail-closed).
    //
    // `input` arrives in the `llm` interface's rich `generateContent` shape
    // (multipart/tool content, reasoning controls, etc.). The boundary adapter
    // narrows it to the SpendGuard pipeline's internal input, runs the gate,
    // then widens the internal result back to the interface output shape.
    generateContent: async ({ input, ctx, logger }) => {
      const result = await runGenerateContent({
        input: toInternalInput(input),
        configuration: ctx.configuration,
        ctx: { botId: ctx.botId, integrationId: ctx.integrationId },
        logger: { warn: (m: string) => logger.forBot().warn(m) },
      });
      return toInterfaceOutput(result);
    },
    listLanguageModels: async ({ ctx }) => {
      return runListLanguageModels(ctx.configuration);
    },
  },
});
