# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from _proto.spendguard.output_predictor_plugin.v1 import plugin_pb2 as spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2

GRPC_GENERATED_VERSION = '1.69.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in spendguard/output_predictor_plugin/v1/plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CustomerPredictorStub(object):
    """Customer-trained output predictor plugin.

    SpendGuard's output_predictor calls Predict synchronously on the
    50ms hot path per spec §4. The plugin MUST respond within 50ms;
    any later = timeout = fall to Strategy B per spec §5.1.

    HealthCheck is called every 30s by the circuit breaker per spec §6.3.
    Not on hot path. NOT_SERVING means SpendGuard skips Predict for this
    tenant until HealthCheck returns SERVING again.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/spendguard.output_predictor_plugin.v1.CustomerPredictor/Predict',
                request_serializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.PredictRequest.SerializeToString,
                response_deserializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/spendguard.output_predictor_plugin.v1.CustomerPredictor/HealthCheck',
                request_serializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class CustomerPredictorServicer(object):
    """Customer-trained output predictor plugin.

    SpendGuard's output_predictor calls Predict synchronously on the
    50ms hot path per spec §4. The plugin MUST respond within 50ms;
    any later = timeout = fall to Strategy B per spec §5.1.

    HealthCheck is called every 30s by the circuit breaker per spec §6.3.
    Not on hot path. NOT_SERVING means SpendGuard skips Predict for this
    tenant until HealthCheck returns SERVING again.
    """

    def Predict(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CustomerPredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.PredictRequest.FromString,
                    response_serializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.PredictResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.HealthCheckRequest.FromString,
                    response_serializer=spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'spendguard.output_predictor_plugin.v1.CustomerPredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('spendguard.output_predictor_plugin.v1.CustomerPredictor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CustomerPredictor(object):
    """Customer-trained output predictor plugin.

    SpendGuard's output_predictor calls Predict synchronously on the
    50ms hot path per spec §4. The plugin MUST respond within 50ms;
    any later = timeout = fall to Strategy B per spec §5.1.

    HealthCheck is called every 30s by the circuit breaker per spec §6.3.
    Not on hot path. NOT_SERVING means SpendGuard skips Predict for this
    tenant until HealthCheck returns SERVING again.
    """

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spendguard.output_predictor_plugin.v1.CustomerPredictor/Predict',
            spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.PredictRequest.SerializeToString,
            spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/spendguard.output_predictor_plugin.v1.CustomerPredictor/HealthCheck',
            spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.HealthCheckRequest.SerializeToString,
            spendguard_dot_output__predictor__plugin_dot_v1_dot_plugin__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
